/* Generated by Nim Compiler v0.16.0 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/usr/local/Cellar/nim/0.16.0/nim/lib -o /Users/jack.sarick/Desktop/land_of_nim/nimcache/chat.o /Users/jack.sarick/Desktop/land_of_nim/nimcache/chat.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <setjmp.h>
#include <sys/socket.h>
#undef linux
typedef struct TY_r7PmaaK9bk3N2VzaDu0773g TY_r7PmaaK9bk3N2VzaDu0773g;
typedef struct Asyncsocketdesc_D7quBEmo0QGfBsms9bXpWfg Asyncsocketdesc_D7quBEmo0QGfBsms9bXpWfg;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct NimStringDesc NimStringDesc;
typedef struct FutureHEX3Aobjecttype_bl7bh8u9cSFPi08mZFnBBvg FutureHEX3Aobjecttype_bl7bh8u9cSFPi08mZFnBBvg;
typedef struct EnvchatHEX2Enim6_9cLknjWm8y9bzwHE4y0Fkp8A EnvchatHEX2Enim6_9cLknjWm8y9bzwHE4y0Fkp8A;
typedef struct FuturebaseHEX3Aobjecttype_9bO2kVCIbVVQatmqvfhtv7w FuturebaseHEX3Aobjecttype_9bO2kVCIbVVQatmqvfhtv7w;
typedef struct Cell_1zcF9cV8XIAtbN8h5HRUB8g Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct Cellseq_Axo1XVm9aaQueTOldv8le5w Cellseq_Axo1XVm9aaQueTOldv8le5w;
typedef struct Gcheap_1TRH1TZMaVZTnLNcIHuNFQ Gcheap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct Gcstack_7fytPA5bBsob6See21YMRA Gcstack_7fytPA5bBsob6See21YMRA;
typedef struct Memregion_x81NhDv59b8ercDZ9bi85jyg Memregion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct Smallchunk_tXn60W2f8h3jgAYdEmy5NQ Smallchunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct Llchunk_XsENErzHIZV9bhvyJx56wGw Llchunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct Bigchunk_Rv9c70Uhp2TytkX7eH78qEg Bigchunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct Intset_EZObFrE3NC9bIb3YMkY9crZA Intset_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct Trunk_W0r8S0Y3UGke6T9bIUWnnuw Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct Avlnode_IaqjtwKhxLEpvDS9bct9blEw Avlnode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct Gcstat_0RwLoVBHZPfUAcLczmfQAg Gcstat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct Cellset_jG87P0AI9aZtss9ccTYBIISQ Cellset_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct Pagedesc_fublkgIY4LG3mT51LU2WHg Pagedesc_fublkgIY4LG3mT51LU2WHg;
typedef struct EnvlibHEX2FpureHEX2FasyncmacroHEX2Enim337_xFNmcra4Uj4tX9a7gFBd4mA EnvlibHEX2FpureHEX2FasyncmacroHEX2Enim337_xFNmcra4Uj4tX9a7gFBd4mA;
typedef struct FutureHEX3Aobjecttype_uVE9bjhVJTXCrEDb8bNN9cuA FutureHEX3Aobjecttype_uVE9bjhVJTXCrEDb8bNN9cuA;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct TSafePoint TSafePoint;
typedef struct FutureHEX3Aobjecttype_gmIfpCSZ9cgWnDwjKXFhXxA FutureHEX3Aobjecttype_gmIfpCSZ9cgWnDwjKXFhXxA;
typedef struct EnvlibHEX2FpureHEX2FasyncmacroHEX2Enim319_OF4bTGyWWMUcvP6Zm2bvKA EnvlibHEX2FpureHEX2FasyncmacroHEX2Enim319_OF4bTGyWWMUcvP6Zm2bvKA;
typedef struct EnvlibHEX2FpureHEX2FasyncmacroHEX2Enim337_h9bthBHwOfI2F06jOR8qr0w EnvlibHEX2FpureHEX2FasyncmacroHEX2Enim337_h9bthBHwOfI2F06jOR8qr0w;
typedef struct Basechunk_Sdq7WpT6qAH858F5ZEdG3w Basechunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct Freecell_u6M5LHprqzkn9axr04yg9bGQ Freecell_u6M5LHprqzkn9axr04yg9bGQ;
struct  TGenericSeq  {
NI len;
NI reserved;
};
typedef NU8 Tnimkind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 Tnimtypeflag_v8QUszD1sWlSIWZz7mC4bQ_Set;
typedef N_NIMCALL_PTR(void, TY_ojoeKfW4VYIm36I9cpDTQIg) (void* p0, NI op0);
typedef N_NIMCALL_PTR(void*, TY_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p0);
struct  TNimType  {
NI size;
Tnimkind_jIBKr1ejBgsfM33Kxw4j7A kind;
Tnimtypeflag_v8QUszD1sWlSIWZz7mC4bQ_Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY_ojoeKfW4VYIm36I9cpDTQIg marker;
TY_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 Tnimnodekind_unfNsxrcATrufDZmpBq4HQ;
struct  TNimNode  {
Tnimnodekind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_NIMCALL_PTR(void, TY_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef struct {
N_NIMCALL_PTR(FuturebaseHEX3Aobjecttype_9bO2kVCIbVVQatmqvfhtv7w*, ClPrc) (void* ClEnv);
void* ClEnv;
} TY_hMF8LVJgm4deTaCKWP1jCg;
struct  EnvchatHEX2Enim6_9cLknjWm8y9bzwHE4y0Fkp8A  {
NI HEX3Astate;
Asyncsocketdesc_D7quBEmo0QGfBsms9bXpWfg* client214015;
FutureHEX3Aobjecttype_bl7bh8u9cSFPi08mZFnBBvg* retfuture214004;
TY_hMF8LVJgm4deTaCKWP1jCg nameitervar214010;
};
struct  Cell_1zcF9cV8XIAtbN8h5HRUB8g  {
NI refcount;
TNimType* typ;
};
struct  Cellseq_Axo1XVm9aaQueTOldv8le5w  {
NI len;
NI cap;
Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef Smallchunk_tXn60W2f8h3jgAYdEmy5NQ* TY_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef Trunk_W0r8S0Y3UGke6T9bIUWnnuw* TY_lh2A89ahMmYg9bCmpVaplLbA[256];
struct  Intset_EZObFrE3NC9bIb3YMkY9crZA  {
TY_lh2A89ahMmYg9bCmpVaplLbA data;
};
struct  Memregion_x81NhDv59b8ercDZ9bi85jyg  {
NI minlargeobj;
NI maxlargeobj;
TY_SiRwrEKZdLgxqz9a9aoVBglg freesmallchunks;
Llchunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk_Rv9c70Uhp2TytkX7eH78qEg* freechunkslist;
Intset_EZObFrE3NC9bIb3YMkY9crZA chunkstarts;
Avlnode_IaqjtwKhxLEpvDS9bct9blEw* root;
Avlnode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
Avlnode_IaqjtwKhxLEpvDS9bct9blEw* last;
Avlnode_IaqjtwKhxLEpvDS9bct9blEw* freeavlnodes;
NIM_BOOL locked;
NIM_BOOL blockchunksizeincrease;
NI nextchunksize;
};
struct  Gcstat_0RwLoVBHZPfUAcLczmfQAg  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Cellset_jG87P0AI9aZtss9ccTYBIISQ  {
NI counter;
NI max;
Pagedesc_fublkgIY4LG3mT51LU2WHg* head;
Pagedesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct  Gcheap_1TRH1TZMaVZTnLNcIHuNFQ  {
Gcstack_7fytPA5bBsob6See21YMRA* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq_Axo1XVm9aaQueTOldv8le5w zct;
Cellseq_Axo1XVm9aaQueTOldv8le5w decstack;
Cellseq_Axo1XVm9aaQueTOldv8le5w tempstack;
NI recgclock;
Memregion_x81NhDv59b8ercDZ9bi85jyg region;
Gcstat_0RwLoVBHZPfUAcLczmfQAg stat;
Cellset_jG87P0AI9aZtss9ccTYBIISQ marked;
Cellseq_Axo1XVm9aaQueTOldv8le5w additionalroots;
};
struct  EnvlibHEX2FpureHEX2FasyncmacroHEX2Enim337_xFNmcra4Uj4tX9a7gFBd4mA  {
NI HEX3Astate;
FutureHEX3Aobjecttype_bl7bh8u9cSFPi08mZFnBBvg* future214006;
EnvchatHEX2Enim6_9cLknjWm8y9bzwHE4y0Fkp8A* HEX3Aup;
FutureHEX3Aobjecttype_uVE9bjhVJTXCrEDb8bNN9cuA* future214007;
NimStringDesc* line214246;
Asyncsocketdesc_D7quBEmo0QGfBsms9bXpWfg* c214255;
NI i214290;
NI L214292;
FutureHEX3Aobjecttype_bl7bh8u9cSFPi08mZFnBBvg* future214008;
};
typedef NU8 Socketflag_4xio0cAXR7XG4pF9bVcpxEg_Set;
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClPrc) (Exception* e0, void* ClEnv);
void* ClEnv;
} TY_KeeAOYBd84Ofsw6Y7LizaQ;
struct  TSafePoint  {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
TY_KeeAOYBd84Ofsw6Y7LizaQ raiseAction;
};
typedef N_CLOSURE_PTR(FuturebaseHEX3Aobjecttype_9bO2kVCIbVVQatmqvfhtv7w*, T_Y4ea819azvvYDURtHxhdboQ_14) (void);
typedef struct {
N_NIMCALL_PTR(void, ClPrc) (void* ClEnv);
void* ClEnv;
} TY_IIomJ6ptE6vfJ5zRbATgkQ;
struct  FuturebaseHEX3Aobjecttype_9bO2kVCIbVVQatmqvfhtv7w  {
  TNimObject Sup;
TY_IIomJ6ptE6vfJ5zRbATgkQ cb;
NIM_BOOL finished;
Exception* error;
NimStringDesc* errorstacktrace;
NimStringDesc* stacktrace;
NI id;
NimStringDesc* fromproc;
};
struct  FutureHEX3Aobjecttype_bl7bh8u9cSFPi08mZFnBBvg  {
  FuturebaseHEX3Aobjecttype_9bO2kVCIbVVQatmqvfhtv7w Sup;
};
typedef N_CLOSURE_PTR(void, T_Y4ea819azvvYDURtHxhdboQ_16) (void);
struct  EnvlibHEX2FpureHEX2FasyncmacroHEX2Enim319_OF4bTGyWWMUcvP6Zm2bvKA  {
NI HEX3Astate;
FutureHEX3Aobjecttype_bl7bh8u9cSFPi08mZFnBBvg* retfuture214435;
TY_hMF8LVJgm4deTaCKWP1jCg nameitervar214439;
};
struct  EnvlibHEX2FpureHEX2FasyncmacroHEX2Enim337_h9bthBHwOfI2F06jOR8qr0w  {
NI HEX3Astate;
Asyncsocketdesc_D7quBEmo0QGfBsms9bXpWfg* server214473;
FutureHEX3Aobjecttype_gmIfpCSZ9cgWnDwjKXFhXxA* future214437;
Asyncsocketdesc_D7quBEmo0QGfBsms9bXpWfg* client214814;
EnvlibHEX2FpureHEX2FasyncmacroHEX2Enim319_OF4bTGyWWMUcvP6Zm2bvKA* HEX3Aup;
};
typedef NU8 Domain_Q79bEtFARvq0ekDNtvj3Vqg;
typedef NU8 Socktype_NQT1bItGG2X9byGdrWX7ujw;
typedef NU8 Protocol_dqJ1OqRGclxIMMdSLRzzXg;
typedef NU8 Sobool_SDlZUtKctfhvUZ58547HWQ;
typedef N_CLOSURE_PTR(FuturebaseHEX3Aobjecttype_9bO2kVCIbVVQatmqvfhtv7w*, T_Y4ea819azvvYDURtHxhdboQ_22) (void);
typedef N_CLOSURE_PTR(void, T_Y4ea819azvvYDURtHxhdboQ_24) (void);
typedef NIM_CHAR TY_QQGLPNVVwLhYjkngqAxXQQ[4001];
struct  Asyncsocketdesc_D7quBEmo0QGfBsms9bXpWfg  {
int fd;
NIM_BOOL closed;
NIM_BOOL isbuffered;
union{
struct {TY_QQGLPNVVwLhYjkngqAxXQQ buffer;
NI currpos;
NI buflen;
} S1;
} isbufferedU;
NIM_BOOL isssl;
Domain_Q79bEtFARvq0ekDNtvj3Vqg domain;
Socktype_NQT1bItGG2X9byGdrWX7ujw socktype;
Protocol_dqJ1OqRGclxIMMdSLRzzXg protocol;
};
struct  Gcstack_7fytPA5bBsob6See21YMRA  {
Gcstack_7fytPA5bBsob6See21YMRA* prev;
Gcstack_7fytPA5bBsob6See21YMRA* next;
void* starts;
void* pos;
NI maxstacksize;
};
struct  Basechunk_Sdq7WpT6qAH858F5ZEdG3w  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk_tXn60W2f8h3jgAYdEmy5NQ  {
  Basechunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
Smallchunk_tXn60W2f8h3jgAYdEmy5NQ* next;
Smallchunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
Freecell_u6M5LHprqzkn9axr04yg9bGQ* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk_XsENErzHIZV9bhvyJx56wGw  {
NI size;
NI acc;
Llchunk_XsENErzHIZV9bhvyJx56wGw* next;
};
struct  Bigchunk_Rv9c70Uhp2TytkX7eH78qEg  {
  Basechunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
Bigchunk_Rv9c70Uhp2TytkX7eH78qEg* next;
Bigchunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NI align;
NF data;
};
typedef NI TY_9a8QARi5WsUggNU9bom7kzTQ[8];
struct  Trunk_W0r8S0Y3UGke6T9bIUWnnuw  {
Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
TY_9a8QARi5WsUggNU9bom7kzTQ bits;
};
typedef Avlnode_IaqjtwKhxLEpvDS9bct9blEw* TY_0aOLqZchNi8nWtMTi8ND8w[2];
struct  Avlnode_IaqjtwKhxLEpvDS9bct9blEw  {
TY_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperbound;
NI level;
};
struct  Pagedesc_fublkgIY4LG3mT51LU2WHg  {
Pagedesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
TY_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct  FutureHEX3Aobjecttype_uVE9bjhVJTXCrEDb8bNN9cuA  {
  FuturebaseHEX3Aobjecttype_9bO2kVCIbVVQatmqvfhtv7w Sup;
NimStringDesc* value;
};
struct  FutureHEX3Aobjecttype_gmIfpCSZ9cgWnDwjKXFhXxA  {
  FuturebaseHEX3Aobjecttype_9bO2kVCIbVVQatmqvfhtv7w Sup;
Asyncsocketdesc_D7quBEmo0QGfBsms9bXpWfg* value;
};
struct  Freecell_u6M5LHprqzkn9axr04yg9bGQ  {
Freecell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zerofield;
};
struct TY_r7PmaaK9bk3N2VzaDu0773g {
  TGenericSeq Sup;
  Asyncsocketdesc_D7quBEmo0QGfBsms9bXpWfg* data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, nimGCvisit)(void* d0, NI op0);
static N_NIMCALL(void, Marker_TY_r7PmaaK9bk3N2VzaDu0773g)(void* p, NI op);
static N_NIMCALL(void, T_Y4ea819azvvYDURtHxhdboQ_2)(void);
N_NIMCALL(void, nimRegisterGlobalMarker)(TY_T4eqaYlFJYZUv9aG9b1TV0bQ markerproc0);
static N_INLINE(NI, find_xDfJOGr8C4W9bDN9ayHMbIawchat)(TY_r7PmaaK9bk3N2VzaDu0773g* a0, Asyncsocketdesc_D7quBEmo0QGfBsms9bXpWfg* item0);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, addInt)(NI a0, NI b0);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(void, failedassertimpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg0);
static N_INLINE(void, nimFrame)(TFrame* s0);
N_NOINLINE(void, stackoverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(FutureHEX3Aobjecttype_bl7bh8u9cSFPi08mZFnBBvg*, processclient_ouDqZMyGHUCDHCgPahH2gg)(Asyncsocketdesc_D7quBEmo0QGfBsms9bXpWfg* client0);
static N_NIMCALL(void, Marker_TY_Fko9cV1i9bRpBx9cYeen2ILOQ)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ0, NI size0);
static N_INLINE(void, asgnRefNoCycle)(void** dest0, void* src0);
static N_INLINE(Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrtocell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr0);
static N_INLINE(void, rtladdzct_MV4BBk6J1qu70IbBxwEn4w_2system)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c0);
N_NOINLINE(void, addzct_fCDI7oO1NNVXXURtxSzsRw)(Cellseq_Axo1XVm9aaQueTOldv8le5w* s0, Cell_1zcF9cV8XIAtbN8h5HRUB8g* c0);
N_NIMCALL(FutureHEX3Aobjecttype_bl7bh8u9cSFPi08mZFnBBvg*, newfuture_G3cvvvURs8ow9aoa6g18ncw)(NimStringDesc* fromproc0);
static N_INLINE(void, asgnRef)(void** dest0, void* src0);
static N_INLINE(void, incref_9cAA5YuQAAC3MVbnGeV86swsystem)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c0);
static N_INLINE(void, decref_MV4BBk6J1qu70IbBxwEn4wsystem)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c0);
static N_NIMCALL(void, Marker_TY_3AX0CJo9anifpFy9aVSHPYXg)(void* p, NI op);
N_CLOSURE(FuturebaseHEX3Aobjecttype_9bO2kVCIbVVQatmqvfhtv7w*, processclientiter_FwpCqkh4zoF81ZW59byNp0A)(void* ClEnv);
N_NIMCALL(FutureHEX3Aobjecttype_bl7bh8u9cSFPi08mZFnBBvg*, send_79bVIiFOJOGQitb8wjd9bIOA)(Asyncsocketdesc_D7quBEmo0QGfBsms9bXpWfg* socket0, NimStringDesc* data0, Socketflag_4xio0cAXR7XG4pF9bVcpxEg_Set flags0);
static N_INLINE(void, appendString)(NimStringDesc* dest0, NimStringDesc* src0);
static N_INLINE(void, copymem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest0, void* source0, NI size0);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x0);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space0);
N_NIMCALL(void, read_mF5KH9ctiyvFvxp6j9b3eqlg)(FutureHEX3Aobjecttype_bl7bh8u9cSFPi08mZFnBBvg* future0);
N_NIMCALL(FutureHEX3Aobjecttype_uVE9bjhVJTXCrEDb8bNN9cuA*, recvline_eqwqayg0FBUxvIZdY0S85Q)(Asyncsocketdesc_D7quBEmo0QGfBsms9bXpWfg* socket0, Socketflag_4xio0cAXR7XG4pF9bVcpxEg_Set flags0, NI maxlength0);
N_NIMCALL(NimStringDesc*, read_Dju8WXYP49bnTJVxhWOJ9c0Q)(FutureHEX3Aobjecttype_uVE9bjhVJTXCrEDb8bNN9cuA* future0);
N_NIMCALL(void, complete_WahSjU7mz9cy8hV9aDbOumwQ_2)(FutureHEX3Aobjecttype_bl7bh8u9cSFPi08mZFnBBvg* future0);
N_CLOSURE(void, cb_5iL7T2rlB1M5Gwameo3UlA)(void* ClEnv);
static N_INLINE(void, pushSafePoint)(TSafePoint* s0);
static N_INLINE(NIM_BOOL, finished_DdCwm9a8Fo6AoGCK7OgPDQwasyncdispatch)(TY_hMF8LVJgm4deTaCKWP1jCg x0);
N_NIMCALL(void, callbackHEX3D_dwNwP9awiBYZ9bwMdZ9b3PAsA)(FuturebaseHEX3Aobjecttype_9bO2kVCIbVVQatmqvfhtv7w* future0, TY_IIomJ6ptE6vfJ5zRbATgkQ cb0);
static N_INLINE(void, popSafePoint)(void);
static N_INLINE(void, setFrame)(TFrame* s0);
N_NIMCALL(void, reraiseException)(void);
N_NIMCALL(void, fail_ItRyHxJqOxe7y9cEgBvDaow)(FutureHEX3Aobjecttype_bl7bh8u9cSFPi08mZFnBBvg* future0, Exception* error0);
static N_INLINE(Exception*, getCurrentException)(void);
static N_INLINE(void, popCurrentException)(void);
N_NIMCALL(Asyncsocketdesc_D7quBEmo0QGfBsms9bXpWfg*, read_SjBzbOh9aWl9auHBqY66m9a0Q)(FutureHEX3Aobjecttype_gmIfpCSZ9cgWnDwjKXFhXxA* future0);
N_NIMCALL(void, injectstacktrace_TNU1Q7sQ5x9a6MKirzkN9coQ)(FutureHEX3Aobjecttype_gmIfpCSZ9cgWnDwjKXFhXxA* future0);
N_NIMCALL(void, asynccheck_WahSjU7mz9cy8hV9aDbOumwQ_3)(FutureHEX3Aobjecttype_bl7bh8u9cSFPi08mZFnBBvg* future0);
N_NIMCALL(FutureHEX3Aobjecttype_bl7bh8u9cSFPi08mZFnBBvg*, serve_RG4z1DHEHLjhFTrGU2RsHA)(void);
static N_NIMCALL(void, Marker_TY_uAN6f0WUvo8vegDEgsMB3g)(void* p, NI op);
static N_NIMCALL(void, Marker_TY_v6ASVpxlmOrrc9cXv9bnJfsA)(void* p, NI op);
N_CLOSURE(FuturebaseHEX3Aobjecttype_9bO2kVCIbVVQatmqvfhtv7w*, serveiter_FwpCqkh4zoF81ZW59byNp0A_2)(void* ClEnv);
static N_INLINE(void, nimGCunrefNoCycle)(void* p0);
N_NIMCALL(void*, newSeqRC1)(TNimType* typ0, NI len0);
N_NIMCALL(Asyncsocketdesc_D7quBEmo0QGfBsms9bXpWfg*, newasyncsocket_Lp9bg27wddAqj9cqLBxmaecA)(Domain_Q79bEtFARvq0ekDNtvj3Vqg domain0, Socktype_NQT1bItGG2X9byGdrWX7ujw socktype0, Protocol_dqJ1OqRGclxIMMdSLRzzXg protocol0, NIM_BOOL buffered0);
N_NIMCALL(void, setsockopt_JPCJhC9bEu9aOoxPq2hoO77A)(Asyncsocketdesc_D7quBEmo0QGfBsms9bXpWfg* socket0, Sobool_SDlZUtKctfhvUZ58547HWQ opt0, NIM_BOOL value0, int level0);
N_NIMCALL(void, bindaddr_NQgoQeDzyOVU5wQsT0aKvw)(Asyncsocketdesc_D7quBEmo0QGfBsms9bXpWfg* socket0, NU16 port0, NimStringDesc* address0);
N_NIMCALL(void, listen_j43wOmhySePrQT9c0LwJhsg)(Asyncsocketdesc_D7quBEmo0QGfBsms9bXpWfg* socket0, int backlog0);
N_NIMCALL(FutureHEX3Aobjecttype_gmIfpCSZ9cgWnDwjKXFhXxA*, accept_0ZYhM3PvCRH0lPBTe1uRHA)(Asyncsocketdesc_D7quBEmo0QGfBsms9bXpWfg* socket0, Socketflag_4xio0cAXR7XG4pF9bVcpxEg_Set flags0);
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq0, NI elemsize0);
N_CLOSURE(void, cb_5iL7T2rlB1M5Gwameo3UlA_2)(void* ClEnv);
N_NIMCALL(void, runforever_jSFKlHW9aWQ06mz9a6ZF5Ylw)(void);
static N_INLINE(void, initStackBottomWith)(void* locals0);
N_NOINLINE(void, setStackBottom)(void* thestackbottom0);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_endiansInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_endiansDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_oidsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_oidsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_etcprivInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_etcprivDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_heapqueueInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_heapqueueDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_nativesocketsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_nativesocketsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_setsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_setsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_netInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_netDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_dequesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_dequesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_kqueueInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_kqueueDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_selectorsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_selectorsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_asyncdispatchInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_asyncdispatchDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_asyncnetInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_asyncnetDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, chatDatInit000)(void);
TY_r7PmaaK9bk3N2VzaDu0773g* clients_Pzf69a3ykbYLfV7QXbwONFA;
extern TNimType NTI_aSlRc15aht0VRnOJAwHxLg;
TNimType NTI_r7PmaaK9bk3N2VzaDu0773g;
extern TFrame* frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw;
TNimType NTI_9cLknjWm8y9bzwHE4y0Fkp8A;
extern TNimType NTI_xHTZrq9aYs6boc9bCba0JbpQ;
extern TNimType NTI_Iud5eP9cpfQsJ8yP1cJOApw;
extern TNimType NTI_hMF8LVJgm4deTaCKWP1jCg;
TNimType NTI_Fko9cV1i9bRpBx9cYeen2ILOQ;
extern Gcheap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
TNimType NTI_xFNmcra4Uj4tX9a7gFBd4mA;
extern TNimType NTI_n4zDRFGzCsBJcFgUikBMgw;
extern TNimType NTI_zlVC9ci9cgyDtfEw4KbxcACA;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA;
TNimType NTI_3AX0CJo9anifpFy9aVSHPYXg;
extern TSafePoint* exchandler_rqLlY5bs9atDw2OXYqJEn5g;
extern Exception* currexception_9bVPeDJlYTi9bQApZpfH8wjg;
TNimType NTI_OF4bTGyWWMUcvP6Zm2bvKA;
TNimType NTI_uAN6f0WUvo8vegDEgsMB3g;
TNimType NTI_h9bthBHwOfI2F06jOR8qr0w;
extern TNimType NTI_Mpt8aZ13tT2AYV71yyfHcA;
extern TNimType NTI_QXDs9ajrOVAncGNEc54sO3g;
TNimType NTI_v6ASVpxlmOrrc9cXv9bnJfsA;
STRING_LITERAL(T_Y4ea819azvvYDURtHxhdboQ_5, "len(a) == L seq modified while iterating over it", 48);
STRING_LITERAL(T_Y4ea819azvvYDURtHxhdboQ_7, "processClient", 13);
STRING_LITERAL(T_Y4ea819azvvYDURtHxhdboQ_9, "Welcome user ", 13);
STRING_LITERAL(T_Y4ea819azvvYDURtHxhdboQ_10, "\015\012", 2);
STRING_LITERAL(T_Y4ea819azvvYDURtHxhdboQ_11, ": ", 2);
STRING_LITERAL(T_Y4ea819azvvYDURtHxhdboQ_15, "retFuture214004.finished Async procedure\'s (processClient) retu"
"rn Future was not finished.", 90);
STRING_LITERAL(T_Y4ea819azvvYDURtHxhdboQ_18, "serve", 5);
STRING_LITERAL(T_Y4ea819azvvYDURtHxhdboQ_20, "", 0);
STRING_LITERAL(T_Y4ea819azvvYDURtHxhdboQ_23, "retFuture214435.finished Async procedure\'s (serve) return Futur"
"e was not finished.", 82);
static N_NIMCALL(void, Marker_TY_r7PmaaK9bk3N2VzaDu0773g)(void* p, NI op) {
	TY_r7PmaaK9bk3N2VzaDu0773g* a;
	NI LOC1;
	a = (TY_r7PmaaK9bk3N2VzaDu0773g*)p;
	LOC1 = (NI)0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1], op);
	}
}
static N_NIMCALL(void, T_Y4ea819azvvYDURtHxhdboQ_2)(void) {
	nimGCvisit((void*)clients_Pzf69a3ykbYLfV7QXbwONFA, 0);
}

static N_INLINE(NI, addInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU64)(a0) + (NU64)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ b0));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

static N_INLINE(void, nimFrame)(TFrame* s0) {
	NI LOC1;
	LOC1 = (NI)0;
	{
		if (!(frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s0).calldepth = ((NI16) (LOC1));
	(*s0).prev = frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw = s0;
	{
		if (!((*s0).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(NI, find_xDfJOGr8C4W9bDN9ayHMbIawchat)(TY_r7PmaaK9bk3N2VzaDu0773g* a0, Asyncsocketdesc_D7quBEmo0QGfBsms9bXpWfg* item0) {
	NI result0;
	nimfr("find", "system.nim")
{	result0 = (NI)0;
	{
		Asyncsocketdesc_D7quBEmo0QGfBsms9bXpWfg* i_PK51OczLhe60IMTnpDtj2Q;
		NI i_PK51OczLhe60IMTnpDtj2Q_2;
		NI L_nNJc8Xj1ehxfKpp6mtkZcw;
		i_PK51OczLhe60IMTnpDtj2Q = (Asyncsocketdesc_D7quBEmo0QGfBsms9bXpWfg*)0;
		nimln(3497, "system.nim");
		i_PK51OczLhe60IMTnpDtj2Q_2 = ((NI) 0);
		nimln(3498, "system.nim");
		nimln(2232, "system.nim");
		L_nNJc8Xj1ehxfKpp6mtkZcw = (a0 ? a0->Sup.len : 0);
		{
			nimln(3499, "system.nim");
			while (1) {
				NI T_Y4ea819azvvYDURtHxhdboQ_3;
				NI T_Y4ea819azvvYDURtHxhdboQ_4;
				nimln(3497, "system.nim");
				if (!(i_PK51OczLhe60IMTnpDtj2Q_2 < L_nNJc8Xj1ehxfKpp6mtkZcw)) goto LA3;
				nimln(3500, "system.nim");
				if ((NU)(i_PK51OczLhe60IMTnpDtj2Q_2) >= (NU)(a0->Sup.len)) raiseIndexError();
				i_PK51OczLhe60IMTnpDtj2Q = a0->data[i_PK51OczLhe60IMTnpDtj2Q_2];
				nimln(2233, "system.nim");
				{
					if (!(i_PK51OczLhe60IMTnpDtj2Q == item0)) goto LA6;
					goto BeforeRet;
				}
				LA6: ;
				nimln(2234, "system.nim");
				T_Y4ea819azvvYDURtHxhdboQ_3 = addInt(result0, ((NI) 1));
				result0 = (NI)(T_Y4ea819azvvYDURtHxhdboQ_3);
				nimln(3497, "system.nim");
				T_Y4ea819azvvYDURtHxhdboQ_4 = addInt(i_PK51OczLhe60IMTnpDtj2Q_2, ((NI) 1));
				i_PK51OczLhe60IMTnpDtj2Q_2 = (NI)(T_Y4ea819azvvYDURtHxhdboQ_4);
				nimln(3502, "system.nim");
				{
					nimln(2232, "system.nim");
					if (!!(((a0 ? a0->Sup.len : 0) == L_nNJc8Xj1ehxfKpp6mtkZcw))) goto LA10;
					nimln(3502, "system.nim");
					failedassertimpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &T_Y4ea819azvvYDURtHxhdboQ_5));
				}
				LA10: ;
			} LA3: ;
		}
	}
	nimln(2235, "system.nim");
	result0 = ((NI) -1);
	}BeforeRet: ;
	popFrame();
	return result0;
}
static N_NIMCALL(void, Marker_TY_Fko9cV1i9bRpBx9cYeen2ILOQ)(void* p, NI op) {
	EnvchatHEX2Enim6_9cLknjWm8y9bzwHE4y0Fkp8A* a;
	a = (EnvchatHEX2Enim6_9cLknjWm8y9bzwHE4y0Fkp8A*)p;
	nimGCvisit((void*)(*a).client214015, op);
	nimGCvisit((void*)(*a).retfuture214004, op);
	nimGCvisit((void*)(*a).nameitervar214010.ClEnv, op);
}

static N_INLINE(Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrtocell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr0) {
	Cell_1zcF9cV8XIAtbN8h5HRUB8g* result0;
	nimfr("usrToCell", "gc.nim")
	result0 = (Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln(134, "gc.nim");
	result0 = ((Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (usr0))) - (NU64)(((NI)sizeof(Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result0;
}

static N_INLINE(void, rtladdzct_MV4BBk6J1qu70IbBxwEn4w_2system)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c0) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(220, "gc.nim");
	addzct_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c0);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest0, void* src0) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(280, "gc.nim");
	{
		Cell_1zcF9cV8XIAtbN8h5HRUB8g* c0;
		nimln(347, "system.nim");
		nimln(280, "gc.nim");
		if (!!((src0 == NIM_NIL))) goto LA3;
		nimln(281, "gc.nim");
		c0 = usrtocell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src0);
		nimln(282, "gc.nim");
		(*c0).refcount += ((NI) 8);
	}
	LA3: ;
	nimln(283, "gc.nim");
	{
		Cell_1zcF9cV8XIAtbN8h5HRUB8g* c0;
		nimln(347, "system.nim");
		nimln(283, "gc.nim");
		if (!!(((*dest0) == NIM_NIL))) goto LA7;
		nimln(284, "gc.nim");
		c0 = usrtocell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest0));
		nimln(285, "gc.nim");
		{
			(*c0).refcount -= ((NI) 8);
			if (!((NU64)((*c0).refcount) < (NU64)(((NI) 8)))) goto LA11;
			nimln(286, "gc.nim");
			rtladdzct_MV4BBk6J1qu70IbBxwEn4w_2system(c0);
		}
		LA11: ;
	}
	LA7: ;
	nimln(287, "gc.nim");
	(*dest0) = src0;
	popFrame();
}

static N_INLINE(void, incref_9cAA5YuQAAC3MVbnGeV86swsystem)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c0) {
	nimfr("incRef", "gc.nim")
	nimln(232, "gc.nim");
	(*c0).refcount = (NI)((NU64)((*c0).refcount) + (NU64)(((NI) 8)));
	popFrame();
}

static N_INLINE(void, decref_MV4BBk6J1qu70IbBxwEn4wsystem)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c0) {
	nimfr("decRef", "gc.nim")
	nimln(227, "gc.nim");
	{
		(*c0).refcount -= ((NI) 8);
		if (!((NU64)((*c0).refcount) < (NU64)(((NI) 8)))) goto LA3;
		nimln(228, "gc.nim");
		rtladdzct_MV4BBk6J1qu70IbBxwEn4w_2system(c0);
	}
	LA3: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest0, void* src0) {
	nimfr("asgnRef", "gc.nim")
	nimln(273, "gc.nim");
	{
		Cell_1zcF9cV8XIAtbN8h5HRUB8g* LOC5;
		nimln(347, "system.nim");
		nimln(273, "gc.nim");
		if (!!((src0 == NIM_NIL))) goto LA3;
		LOC5 = (Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		LOC5 = usrtocell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src0);
		incref_9cAA5YuQAAC3MVbnGeV86swsystem(LOC5);
	}
	LA3: ;
	nimln(274, "gc.nim");
	{
		Cell_1zcF9cV8XIAtbN8h5HRUB8g* LOC10;
		nimln(347, "system.nim");
		nimln(274, "gc.nim");
		if (!!(((*dest0) == NIM_NIL))) goto LA8;
		LOC10 = (Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		LOC10 = usrtocell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest0));
		decref_MV4BBk6J1qu70IbBxwEn4wsystem(LOC10);
	}
	LA8: ;
	nimln(275, "gc.nim");
	(*dest0) = src0;
	popFrame();
}
static N_NIMCALL(void, Marker_TY_3AX0CJo9anifpFy9aVSHPYXg)(void* p, NI op) {
	EnvlibHEX2FpureHEX2FasyncmacroHEX2Enim337_xFNmcra4Uj4tX9a7gFBd4mA* a;
	a = (EnvlibHEX2FpureHEX2FasyncmacroHEX2Enim337_xFNmcra4Uj4tX9a7gFBd4mA*)p;
	nimGCvisit((void*)(*a).future214006, op);
	nimGCvisit((void*)(*a).HEX3Aup, op);
	nimGCvisit((void*)(*a).future214007, op);
	nimGCvisit((void*)(*a).line214246, op);
	nimGCvisit((void*)(*a).c214255, op);
	nimGCvisit((void*)(*a).future214008, op);
}

static N_INLINE(void, copymem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest0, void* source0, NI size0) {
	void* LOC1;
	LOC1 = (void*)0;
	LOC1 = memcpy(dest0, source0, ((size_t) (size0)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest0, NimStringDesc* src0) {
	copymem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest0).data[((*dest0).Sup.len)- 0]))), ((void*) ((*src0).data)), ((NI) ((NI)((*src0).Sup.len + ((NI) 1)))));
	(*dest0).Sup.len += (*src0).Sup.len;
}

N_CLOSURE(FuturebaseHEX3Aobjecttype_9bO2kVCIbVVQatmqvfhtv7w*, processclientiter_FwpCqkh4zoF81ZW59byNp0A)(void* ClEnv) {
	FuturebaseHEX3Aobjecttype_9bO2kVCIbVVQatmqvfhtv7w* result0;
	EnvlibHEX2FpureHEX2FasyncmacroHEX2Enim337_xFNmcra4Uj4tX9a7gFBd4mA* HEX3Aenvp_BWD6GlEy9cQX0Y1WQXRVKAQ;
	NimStringDesc* LOC1;
	NI LOC2;
	NimStringDesc* LOC3;
	nimfr("processClientIter", "asyncmacro.nim")
{	result0 = (FuturebaseHEX3Aobjecttype_9bO2kVCIbVVQatmqvfhtv7w*)0;
	HEX3Aenvp_BWD6GlEy9cQX0Y1WQXRVKAQ = (EnvlibHEX2FpureHEX2FasyncmacroHEX2Enim337_xFNmcra4Uj4tX9a7gFBd4mA*) ClEnv;
	switch ((*HEX3Aenvp_BWD6GlEy9cQX0Y1WQXRVKAQ).HEX3Astate) {
	case -1: goto BeforeRet;
	case 0: goto STATE0;
	case 1: goto STATE1;
	case 2: goto STATE2;
	case 3: goto STATE3;
	}
	STATE0: ;
	nimln(6, "chat.nim");
	LOC1 = (NimStringDesc*)0;
	LOC2 = (NI)0;
	LOC2 = find_xDfJOGr8C4W9bDN9ayHMbIawchat(clients_Pzf69a3ykbYLfV7QXbwONFA, (*(*HEX3Aenvp_BWD6GlEy9cQX0Y1WQXRVKAQ).HEX3Aup).client214015);
	LOC3 = (NimStringDesc*)0;
	LOC3 = nimIntToStr(LOC2);
	LOC1 = rawNewString(LOC3->Sup.len + 15);
appendString(LOC1, ((NimStringDesc*) &T_Y4ea819azvvYDURtHxhdboQ_9));
appendString(LOC1, LOC3);
appendString(LOC1, ((NimStringDesc*) &T_Y4ea819azvvYDURtHxhdboQ_10));
	asgnRef((void**) (&(*HEX3Aenvp_BWD6GlEy9cQX0Y1WQXRVKAQ).future214006), send_79bVIiFOJOGQitb8wjd9bIOA((*(*HEX3Aenvp_BWD6GlEy9cQX0Y1WQXRVKAQ).HEX3Aup).client214015, LOC1, 2));
	(*HEX3Aenvp_BWD6GlEy9cQX0Y1WQXRVKAQ).HEX3Astate = ((NI) 1);
	nimln(120, "asyncmacro.nim");
	result0 = &(*HEX3Aenvp_BWD6GlEy9cQX0Y1WQXRVKAQ).future214006->Sup;
	goto BeforeRet;
	STATE1: ;
	read_mF5KH9ctiyvFvxp6j9b3eqlg((*HEX3Aenvp_BWD6GlEy9cQX0Y1WQXRVKAQ).future214006);
	{
		nimln(8, "chat.nim");
		while (1) {
			nimln(9, "chat.nim");
			asgnRef((void**) (&(*HEX3Aenvp_BWD6GlEy9cQX0Y1WQXRVKAQ).future214007), recvline_eqwqayg0FBUxvIZdY0S85Q((*(*HEX3Aenvp_BWD6GlEy9cQX0Y1WQXRVKAQ).HEX3Aup).client214015, 2, ((NI) 1000000)));
			(*HEX3Aenvp_BWD6GlEy9cQX0Y1WQXRVKAQ).HEX3Astate = ((NI) 2);
			nimln(120, "asyncmacro.nim");
			result0 = &(*HEX3Aenvp_BWD6GlEy9cQX0Y1WQXRVKAQ).future214007->Sup;
			goto BeforeRet;
			STATE2: ;
			nimln(9, "chat.nim");
			asgnRefNoCycle((void**) (&(*HEX3Aenvp_BWD6GlEy9cQX0Y1WQXRVKAQ).line214246), read_Dju8WXYP49bnTJVxhWOJ9c0Q((*HEX3Aenvp_BWD6GlEy9cQX0Y1WQXRVKAQ).future214007));
			nimln(10, "chat.nim");
			{
				if (!(((*HEX3Aenvp_BWD6GlEy9cQX0Y1WQXRVKAQ).line214246 ? (*HEX3Aenvp_BWD6GlEy9cQX0Y1WQXRVKAQ).line214246->Sup.len : 0) == ((NI) 0))) goto LA8;
				goto LA4;
			}
			LA8: ;
			{
				nimln(3497, "system.nim");
				(*HEX3Aenvp_BWD6GlEy9cQX0Y1WQXRVKAQ).i214290 = ((NI) 0);
				nimln(3498, "system.nim");
				nimln(11, "chat.nim");
				(*HEX3Aenvp_BWD6GlEy9cQX0Y1WQXRVKAQ).L214292 = (clients_Pzf69a3ykbYLfV7QXbwONFA ? clients_Pzf69a3ykbYLfV7QXbwONFA->Sup.len : 0);
				{
					nimln(3499, "system.nim");
					while (1) {
						NI T_Y4ea819azvvYDURtHxhdboQ_12;
						nimln(3497, "system.nim");
						if (!((*HEX3Aenvp_BWD6GlEy9cQX0Y1WQXRVKAQ).i214290 < (*HEX3Aenvp_BWD6GlEy9cQX0Y1WQXRVKAQ).L214292)) goto LA12;
						nimln(3500, "system.nim");
						if ((NU)((*HEX3Aenvp_BWD6GlEy9cQX0Y1WQXRVKAQ).i214290) >= (NU)(clients_Pzf69a3ykbYLfV7QXbwONFA->Sup.len)) raiseIndexError();
						asgnRefNoCycle((void**) (&(*HEX3Aenvp_BWD6GlEy9cQX0Y1WQXRVKAQ).c214255), clients_Pzf69a3ykbYLfV7QXbwONFA->data[(*HEX3Aenvp_BWD6GlEy9cQX0Y1WQXRVKAQ).i214290]);
						nimln(12, "chat.nim");
						{
							NimStringDesc* LOC17;
							NI LOC18;
							NimStringDesc* LOC19;
							nimln(347, "system.nim");
							nimln(12, "chat.nim");
							if (!!(((*HEX3Aenvp_BWD6GlEy9cQX0Y1WQXRVKAQ).c214255 == (*(*HEX3Aenvp_BWD6GlEy9cQX0Y1WQXRVKAQ).HEX3Aup).client214015))) goto LA15;
							nimln(13, "chat.nim");
							LOC17 = (NimStringDesc*)0;
							LOC18 = (NI)0;
							LOC18 = find_xDfJOGr8C4W9bDN9ayHMbIawchat(clients_Pzf69a3ykbYLfV7QXbwONFA, (*(*HEX3Aenvp_BWD6GlEy9cQX0Y1WQXRVKAQ).HEX3Aup).client214015);
							LOC19 = (NimStringDesc*)0;
							LOC19 = nimIntToStr(LOC18);
							LOC17 = rawNewString(LOC19->Sup.len + (*HEX3Aenvp_BWD6GlEy9cQX0Y1WQXRVKAQ).line214246->Sup.len + 4);
appendString(LOC17, LOC19);
appendString(LOC17, ((NimStringDesc*) &T_Y4ea819azvvYDURtHxhdboQ_11));
appendString(LOC17, (*HEX3Aenvp_BWD6GlEy9cQX0Y1WQXRVKAQ).line214246);
appendString(LOC17, ((NimStringDesc*) &T_Y4ea819azvvYDURtHxhdboQ_10));
							asgnRef((void**) (&(*HEX3Aenvp_BWD6GlEy9cQX0Y1WQXRVKAQ).future214008), send_79bVIiFOJOGQitb8wjd9bIOA((*HEX3Aenvp_BWD6GlEy9cQX0Y1WQXRVKAQ).c214255, LOC17, 2));
							(*HEX3Aenvp_BWD6GlEy9cQX0Y1WQXRVKAQ).HEX3Astate = ((NI) 3);
							nimln(120, "asyncmacro.nim");
							result0 = &(*HEX3Aenvp_BWD6GlEy9cQX0Y1WQXRVKAQ).future214008->Sup;
							goto BeforeRet;
							STATE3: ;
							read_mF5KH9ctiyvFvxp6j9b3eqlg((*HEX3Aenvp_BWD6GlEy9cQX0Y1WQXRVKAQ).future214008);
						}
						LA15: ;
						nimln(3497, "system.nim");
						T_Y4ea819azvvYDURtHxhdboQ_12 = addInt((*HEX3Aenvp_BWD6GlEy9cQX0Y1WQXRVKAQ).i214290, ((NI) 1));
						(*HEX3Aenvp_BWD6GlEy9cQX0Y1WQXRVKAQ).i214290 = (NI)(T_Y4ea819azvvYDURtHxhdboQ_12);
						nimln(3502, "system.nim");
						{
							nimln(11, "chat.nim");
							if (!!(((clients_Pzf69a3ykbYLfV7QXbwONFA ? clients_Pzf69a3ykbYLfV7QXbwONFA->Sup.len : 0) == (*HEX3Aenvp_BWD6GlEy9cQX0Y1WQXRVKAQ).L214292))) goto LA22;
							nimln(3502, "system.nim");
							failedassertimpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &T_Y4ea819azvvYDURtHxhdboQ_5));
						}
						LA22: ;
					} LA12: ;
				}
			}
		}
	} LA4: ;
	nimln(319, "asyncmacro.nim");
	complete_WahSjU7mz9cy8hV9aDbOumwQ_2((*(*HEX3Aenvp_BWD6GlEy9cQX0Y1WQXRVKAQ).HEX3Aup).retfuture214004);
	nimln(6, "chat.nim");
	(*HEX3Aenvp_BWD6GlEy9cQX0Y1WQXRVKAQ).HEX3Astate = ((NI) -1);
	}BeforeRet: ;
	popFrame();
	return result0;
}

static N_INLINE(void, pushSafePoint)(TSafePoint* s0) {
	(*s0).hasRaiseAction = NIM_FALSE;
	(*s0).prev = exchandler_rqLlY5bs9atDw2OXYqJEn5g;
	exchandler_rqLlY5bs9atDw2OXYqJEn5g = s0;
}

static N_INLINE(NIM_BOOL, finished_DdCwm9a8Fo6AoGCK7OgPDQwasyncdispatch)(TY_hMF8LVJgm4deTaCKWP1jCg x0) {
	NIM_BOOL result0;
	nimfr("finished", "system.nim")
	result0 = (NIM_BOOL)0;
	nimln(3136, "system.nim");
	      result0 = *((NI*) x0.ClEnv) < 0;
      
	popFrame();
	return result0;
}

static N_INLINE(void, popSafePoint)(void) {
	exchandler_rqLlY5bs9atDw2OXYqJEn5g = (*exchandler_rqLlY5bs9atDw2OXYqJEn5g).prev;
}

static N_INLINE(void, setFrame)(TFrame* s0) {
	frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw = s0;
}

static N_INLINE(Exception*, getCurrentException)(void) {
	Exception* result0;
	nimfr("getCurrentException", "system.nim")
	result0 = (Exception*)0;
	nimln(3087, "system.nim");
	result0 = currexception_9bVPeDJlYTi9bQApZpfH8wjg;
	popFrame();
	return result0;
}

static N_INLINE(void, popCurrentException)(void) {
	asgnRef((void**) (&currexception_9bVPeDJlYTi9bQApZpfH8wjg), NIM_NIL);
}

N_CLOSURE(void, cb_5iL7T2rlB1M5Gwameo3UlA)(void* ClEnv) {
	EnvchatHEX2Enim6_9cLknjWm8y9bzwHE4y0Fkp8A* HEX3Aenvp_o9ceNzHls7yxWE3hxXmiNYw;
	TSafePoint T_Y4ea819azvvYDURtHxhdboQ_13;
	nimfr("cb", "asyncmacro.nim")
	HEX3Aenvp_o9ceNzHls7yxWE3hxXmiNYw = (EnvchatHEX2Enim6_9cLknjWm8y9bzwHE4y0Fkp8A*) ClEnv;
	nimln(32, "asyncmacro.nim");
	pushSafePoint(&T_Y4ea819azvvYDURtHxhdboQ_13);
	T_Y4ea819azvvYDURtHxhdboQ_13.status = _setjmp(T_Y4ea819azvvYDURtHxhdboQ_13.context);
	if (T_Y4ea819azvvYDURtHxhdboQ_13.status == 0) {
		nimln(33, "asyncmacro.nim");
		{
			NIM_BOOL LOC4;
			FuturebaseHEX3Aobjecttype_9bO2kVCIbVVQatmqvfhtv7w* next_YgFxUll9cpSx0m3ZMdFbM3g;
			LOC4 = (NIM_BOOL)0;
			LOC4 = finished_DdCwm9a8Fo6AoGCK7OgPDQwasyncdispatch((*HEX3Aenvp_o9ceNzHls7yxWE3hxXmiNYw).nameitervar214010);
			if (!!(LOC4)) goto LA5;
			nimln(34, "asyncmacro.nim");
			next_YgFxUll9cpSx0m3ZMdFbM3g = (*HEX3Aenvp_o9ceNzHls7yxWE3hxXmiNYw).nameitervar214010.ClPrc((*HEX3Aenvp_o9ceNzHls7yxWE3hxXmiNYw).nameitervar214010.ClEnv);
			nimln(35, "asyncmacro.nim");
			{
				if (!(next_YgFxUll9cpSx0m3ZMdFbM3g == NIM_NIL)) goto LA9;
				nimln(36, "asyncmacro.nim");
				{
					if (!!((*(*HEX3Aenvp_o9ceNzHls7yxWE3hxXmiNYw).retfuture214004).Sup.finished)) goto LA13;
					failedassertimpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &T_Y4ea819azvvYDURtHxhdboQ_15));
				}
				LA13: ;
			}
			goto LA7;
			LA9: ;
			{
				TY_IIomJ6ptE6vfJ5zRbATgkQ LOC16;
				nimln(39, "asyncmacro.nim");
				memset((void*)(&LOC16), 0, sizeof(LOC16));
				LOC16.ClPrc = cb_5iL7T2rlB1M5Gwameo3UlA; LOC16.ClEnv = HEX3Aenvp_o9ceNzHls7yxWE3hxXmiNYw;
				callbackHEX3D_dwNwP9awiBYZ9bwMdZ9b3PAsA(next_YgFxUll9cpSx0m3ZMdFbM3g, LOC16);
			}
			LA7: ;
		}
		LA5: ;
		popSafePoint();
	}
	else {
		popSafePoint();
		setFrame((TFrame*)&FR);
		{
			T_Y4ea819azvvYDURtHxhdboQ_13.status = 0;
			nimln(41, "asyncmacro.nim");
			{
				if (!(*(*HEX3Aenvp_o9ceNzHls7yxWE3hxXmiNYw).retfuture214004).Sup.finished) goto LA21;
				nimln(44, "asyncmacro.nim");
				reraiseException();
			}
			goto LA19;
			LA21: ;
			{
				Exception* LOC24;
				nimln(319, "asyncmacro.nim");
				nimln(46, "asyncmacro.nim");
				LOC24 = (Exception*)0;
				LOC24 = getCurrentException();
				fail_ItRyHxJqOxe7y9cEgBvDaow((*HEX3Aenvp_o9ceNzHls7yxWE3hxXmiNYw).retfuture214004, LOC24);
			}
			LA19: ;
			popCurrentException();
		}
	}
	if (T_Y4ea819azvvYDURtHxhdboQ_13.status != 0) reraiseException();
	popFrame();
}

N_NIMCALL(FutureHEX3Aobjecttype_bl7bh8u9cSFPi08mZFnBBvg*, processclient_ouDqZMyGHUCDHCgPahH2gg)(Asyncsocketdesc_D7quBEmo0QGfBsms9bXpWfg* client0) {
	FutureHEX3Aobjecttype_bl7bh8u9cSFPi08mZFnBBvg* result0;
	EnvchatHEX2Enim6_9cLknjWm8y9bzwHE4y0Fkp8A* HEX3Aenv_TIWc7gHUR5qN53tIEVOaMA;
	EnvlibHEX2FpureHEX2FasyncmacroHEX2Enim337_xFNmcra4Uj4tX9a7gFBd4mA* HEX3Aenv_TIWc7gHUR5qN53tIEVOaMA_2;
	TY_hMF8LVJgm4deTaCKWP1jCg LOC1;
	TY_IIomJ6ptE6vfJ5zRbATgkQ LOC2;
	nimfr("processClient", "chat.nim")
{	result0 = (FutureHEX3Aobjecttype_bl7bh8u9cSFPi08mZFnBBvg*)0;
	HEX3Aenv_TIWc7gHUR5qN53tIEVOaMA = (EnvchatHEX2Enim6_9cLknjWm8y9bzwHE4y0Fkp8A*)0;
	nimln(5, "chat.nim");
	HEX3Aenv_TIWc7gHUR5qN53tIEVOaMA = (EnvchatHEX2Enim6_9cLknjWm8y9bzwHE4y0Fkp8A*) newObj((&NTI_Fko9cV1i9bRpBx9cYeen2ILOQ), sizeof(EnvchatHEX2Enim6_9cLknjWm8y9bzwHE4y0Fkp8A));
	asgnRefNoCycle((void**) (&(*HEX3Aenv_TIWc7gHUR5qN53tIEVOaMA).client214015), client0);
	asgnRef((void**) (&(*HEX3Aenv_TIWc7gHUR5qN53tIEVOaMA).retfuture214004), newfuture_G3cvvvURs8ow9aoa6g18ncw(((NimStringDesc*) &T_Y4ea819azvvYDURtHxhdboQ_7)));
	nimln(29, "asyncmacro.nim");
	HEX3Aenv_TIWc7gHUR5qN53tIEVOaMA_2 = (EnvlibHEX2FpureHEX2FasyncmacroHEX2Enim337_xFNmcra4Uj4tX9a7gFBd4mA*)0;
	nimln(337, "asyncmacro.nim");
	HEX3Aenv_TIWc7gHUR5qN53tIEVOaMA_2 = (EnvlibHEX2FpureHEX2FasyncmacroHEX2Enim337_xFNmcra4Uj4tX9a7gFBd4mA*) newObj((&NTI_3AX0CJo9anifpFy9aVSHPYXg), sizeof(EnvlibHEX2FpureHEX2FasyncmacroHEX2Enim337_xFNmcra4Uj4tX9a7gFBd4mA));
	asgnRef((void**) (&(*HEX3Aenv_TIWc7gHUR5qN53tIEVOaMA_2).HEX3Aup), HEX3Aenv_TIWc7gHUR5qN53tIEVOaMA);
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.ClPrc = processclientiter_FwpCqkh4zoF81ZW59byNp0A; LOC1.ClEnv = HEX3Aenv_TIWc7gHUR5qN53tIEVOaMA_2;
	asgnRef((void**) (&(*HEX3Aenv_TIWc7gHUR5qN53tIEVOaMA).nameitervar214010.ClEnv), LOC1.ClEnv);
	(*HEX3Aenv_TIWc7gHUR5qN53tIEVOaMA).nameitervar214010.ClPrc = LOC1.ClPrc;
	nimln(370, "asyncmacro.nim");
	memset((void*)(&LOC2), 0, sizeof(LOC2));
	LOC2.ClPrc = cb_5iL7T2rlB1M5Gwameo3UlA; LOC2.ClEnv = HEX3Aenv_TIWc7gHUR5qN53tIEVOaMA;
	LOC2.ClEnv? LOC2.ClPrc(LOC2.ClEnv):((T_Y4ea819azvvYDURtHxhdboQ_16)(LOC2.ClPrc))();
	nimln(6, "chat.nim");
	nimln(319, "asyncmacro.nim");
	result0 = (*HEX3Aenv_TIWc7gHUR5qN53tIEVOaMA).retfuture214004;
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result0;
}
static N_NIMCALL(void, Marker_TY_uAN6f0WUvo8vegDEgsMB3g)(void* p, NI op) {
	EnvlibHEX2FpureHEX2FasyncmacroHEX2Enim319_OF4bTGyWWMUcvP6Zm2bvKA* a;
	a = (EnvlibHEX2FpureHEX2FasyncmacroHEX2Enim319_OF4bTGyWWMUcvP6Zm2bvKA*)p;
	nimGCvisit((void*)(*a).retfuture214435, op);
	nimGCvisit((void*)(*a).nameitervar214439.ClEnv, op);
}
static N_NIMCALL(void, Marker_TY_v6ASVpxlmOrrc9cXv9bnJfsA)(void* p, NI op) {
	EnvlibHEX2FpureHEX2FasyncmacroHEX2Enim337_h9bthBHwOfI2F06jOR8qr0w* a;
	a = (EnvlibHEX2FpureHEX2FasyncmacroHEX2Enim337_h9bthBHwOfI2F06jOR8qr0w*)p;
	nimGCvisit((void*)(*a).server214473, op);
	nimGCvisit((void*)(*a).future214437, op);
	nimGCvisit((void*)(*a).client214814, op);
	nimGCvisit((void*)(*a).HEX3Aup, op);
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p0) {
	Cell_1zcF9cV8XIAtbN8h5HRUB8g* c0;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(262, "gc.nim");
	c0 = usrtocell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p0);
	nimln(264, "gc.nim");
	{
		(*c0).refcount -= ((NI) 8);
		if (!((NU64)((*c0).refcount) < (NU64)(((NI) 8)))) goto LA3;
		nimln(265, "gc.nim");
		rtladdzct_MV4BBk6J1qu70IbBxwEn4w_2system(c0);
	}
	LA3: ;
	popFrame();
}

N_CLOSURE(FuturebaseHEX3Aobjecttype_9bO2kVCIbVVQatmqvfhtv7w*, serveiter_FwpCqkh4zoF81ZW59byNp0A_2)(void* ClEnv) {
	FuturebaseHEX3Aobjecttype_9bO2kVCIbVVQatmqvfhtv7w* result0;
	EnvlibHEX2FpureHEX2FasyncmacroHEX2Enim337_h9bthBHwOfI2F06jOR8qr0w* HEX3Aenvp_tkWlJL2Yhd5ZfzZqYUCJcA;
	nimfr("serveIter", "asyncmacro.nim")
{	result0 = (FuturebaseHEX3Aobjecttype_9bO2kVCIbVVQatmqvfhtv7w*)0;
	HEX3Aenvp_tkWlJL2Yhd5ZfzZqYUCJcA = (EnvlibHEX2FpureHEX2FasyncmacroHEX2Enim337_h9bthBHwOfI2F06jOR8qr0w*) ClEnv;
	switch ((*HEX3Aenvp_tkWlJL2Yhd5ZfzZqYUCJcA).HEX3Astate) {
	case -1: goto BeforeRet;
	case 0: goto STATE0;
	case 1: goto STATE1;
	}
	STATE0: ;
	nimln(16, "chat.nim");
	if (clients_Pzf69a3ykbYLfV7QXbwONFA) nimGCunrefNoCycle(clients_Pzf69a3ykbYLfV7QXbwONFA);
	clients_Pzf69a3ykbYLfV7QXbwONFA = (TY_r7PmaaK9bk3N2VzaDu0773g*) newSeqRC1((&NTI_r7PmaaK9bk3N2VzaDu0773g), 0);
	nimln(17, "chat.nim");
	asgnRefNoCycle((void**) (&(*HEX3Aenvp_tkWlJL2Yhd5ZfzZqYUCJcA).server214473), newasyncsocket_Lp9bg27wddAqj9cqLBxmaecA(((Domain_Q79bEtFARvq0ekDNtvj3Vqg) 2), ((Socktype_NQT1bItGG2X9byGdrWX7ujw) 1), ((Protocol_dqJ1OqRGclxIMMdSLRzzXg) 6), NIM_TRUE));
	nimln(18, "chat.nim");
	setsockopt_JPCJhC9bEu9aOoxPq2hoO77A((*HEX3Aenvp_tkWlJL2Yhd5ZfzZqYUCJcA).server214473, ((Sobool_SDlZUtKctfhvUZ58547HWQ) 6), NIM_TRUE, SOL_SOCKET);
	nimln(19, "chat.nim");
	bindaddr_NQgoQeDzyOVU5wQsT0aKvw((*HEX3Aenvp_tkWlJL2Yhd5ZfzZqYUCJcA).server214473, ((NU16) 12345), ((NimStringDesc*) &T_Y4ea819azvvYDURtHxhdboQ_20));
	nimln(20, "chat.nim");
	listen_j43wOmhySePrQT9c0LwJhsg((*HEX3Aenvp_tkWlJL2Yhd5ZfzZqYUCJcA).server214473, SOMAXCONN);
	{
		nimln(22, "chat.nim");
		while (1) {
			FutureHEX3Aobjecttype_bl7bh8u9cSFPi08mZFnBBvg* LOC3;
			nimln(23, "chat.nim");
			asgnRef((void**) (&(*HEX3Aenvp_tkWlJL2Yhd5ZfzZqYUCJcA).future214437), accept_0ZYhM3PvCRH0lPBTe1uRHA((*HEX3Aenvp_tkWlJL2Yhd5ZfzZqYUCJcA).server214473, 2));
			(*HEX3Aenvp_tkWlJL2Yhd5ZfzZqYUCJcA).HEX3Astate = ((NI) 1);
			nimln(120, "asyncmacro.nim");
			result0 = &(*HEX3Aenvp_tkWlJL2Yhd5ZfzZqYUCJcA).future214437->Sup;
			goto BeforeRet;
			STATE1: ;
			nimln(23, "chat.nim");
			asgnRefNoCycle((void**) (&(*HEX3Aenvp_tkWlJL2Yhd5ZfzZqYUCJcA).client214814), read_SjBzbOh9aWl9auHBqY66m9a0Q((*HEX3Aenvp_tkWlJL2Yhd5ZfzZqYUCJcA).future214437));
			nimln(24, "chat.nim");
			clients_Pzf69a3ykbYLfV7QXbwONFA = (TY_r7PmaaK9bk3N2VzaDu0773g*) incrSeqV2(&(clients_Pzf69a3ykbYLfV7QXbwONFA)->Sup, sizeof(Asyncsocketdesc_D7quBEmo0QGfBsms9bXpWfg*));
			asgnRefNoCycle((void**) (&clients_Pzf69a3ykbYLfV7QXbwONFA->data[clients_Pzf69a3ykbYLfV7QXbwONFA->Sup.len]), (*HEX3Aenvp_tkWlJL2Yhd5ZfzZqYUCJcA).client214814);
			++clients_Pzf69a3ykbYLfV7QXbwONFA->Sup.len;
			nimln(26, "chat.nim");
			LOC3 = (FutureHEX3Aobjecttype_bl7bh8u9cSFPi08mZFnBBvg*)0;
			LOC3 = processclient_ouDqZMyGHUCDHCgPahH2gg((*HEX3Aenvp_tkWlJL2Yhd5ZfzZqYUCJcA).client214814);
			asynccheck_WahSjU7mz9cy8hV9aDbOumwQ_3(LOC3);
		}
	}
	nimln(319, "asyncmacro.nim");
	complete_WahSjU7mz9cy8hV9aDbOumwQ_2((*(*HEX3Aenvp_tkWlJL2Yhd5ZfzZqYUCJcA).HEX3Aup).retfuture214435);
	nimln(16, "chat.nim");
	(*HEX3Aenvp_tkWlJL2Yhd5ZfzZqYUCJcA).HEX3Astate = ((NI) -1);
	}BeforeRet: ;
	popFrame();
	return result0;
}

N_CLOSURE(void, cb_5iL7T2rlB1M5Gwameo3UlA_2)(void* ClEnv) {
	EnvlibHEX2FpureHEX2FasyncmacroHEX2Enim319_OF4bTGyWWMUcvP6Zm2bvKA* HEX3Aenvp_9c0mKMU5cZDlDz1SKPE9an9aw;
	TSafePoint T_Y4ea819azvvYDURtHxhdboQ_21;
	nimfr("cb", "asyncmacro.nim")
	HEX3Aenvp_9c0mKMU5cZDlDz1SKPE9an9aw = (EnvlibHEX2FpureHEX2FasyncmacroHEX2Enim319_OF4bTGyWWMUcvP6Zm2bvKA*) ClEnv;
	nimln(32, "asyncmacro.nim");
	pushSafePoint(&T_Y4ea819azvvYDURtHxhdboQ_21);
	T_Y4ea819azvvYDURtHxhdboQ_21.status = _setjmp(T_Y4ea819azvvYDURtHxhdboQ_21.context);
	if (T_Y4ea819azvvYDURtHxhdboQ_21.status == 0) {
		nimln(33, "asyncmacro.nim");
		{
			NIM_BOOL LOC4;
			FuturebaseHEX3Aobjecttype_9bO2kVCIbVVQatmqvfhtv7w* next_OaYLrQnmx9cvxpzMebIxryQ;
			LOC4 = (NIM_BOOL)0;
			LOC4 = finished_DdCwm9a8Fo6AoGCK7OgPDQwasyncdispatch((*HEX3Aenvp_9c0mKMU5cZDlDz1SKPE9an9aw).nameitervar214439);
			if (!!(LOC4)) goto LA5;
			nimln(34, "asyncmacro.nim");
			next_OaYLrQnmx9cvxpzMebIxryQ = (*HEX3Aenvp_9c0mKMU5cZDlDz1SKPE9an9aw).nameitervar214439.ClPrc((*HEX3Aenvp_9c0mKMU5cZDlDz1SKPE9an9aw).nameitervar214439.ClEnv);
			nimln(35, "asyncmacro.nim");
			{
				if (!(next_OaYLrQnmx9cvxpzMebIxryQ == NIM_NIL)) goto LA9;
				nimln(36, "asyncmacro.nim");
				{
					if (!!((*(*HEX3Aenvp_9c0mKMU5cZDlDz1SKPE9an9aw).retfuture214435).Sup.finished)) goto LA13;
					failedassertimpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &T_Y4ea819azvvYDURtHxhdboQ_23));
				}
				LA13: ;
			}
			goto LA7;
			LA9: ;
			{
				TY_IIomJ6ptE6vfJ5zRbATgkQ LOC16;
				nimln(39, "asyncmacro.nim");
				memset((void*)(&LOC16), 0, sizeof(LOC16));
				LOC16.ClPrc = cb_5iL7T2rlB1M5Gwameo3UlA_2; LOC16.ClEnv = HEX3Aenvp_9c0mKMU5cZDlDz1SKPE9an9aw;
				callbackHEX3D_dwNwP9awiBYZ9bwMdZ9b3PAsA(next_OaYLrQnmx9cvxpzMebIxryQ, LOC16);
			}
			LA7: ;
		}
		LA5: ;
		popSafePoint();
	}
	else {
		popSafePoint();
		setFrame((TFrame*)&FR);
		{
			T_Y4ea819azvvYDURtHxhdboQ_21.status = 0;
			nimln(41, "asyncmacro.nim");
			{
				if (!(*(*HEX3Aenvp_9c0mKMU5cZDlDz1SKPE9an9aw).retfuture214435).Sup.finished) goto LA21;
				nimln(44, "asyncmacro.nim");
				reraiseException();
			}
			goto LA19;
			LA21: ;
			{
				Exception* LOC24;
				nimln(319, "asyncmacro.nim");
				nimln(46, "asyncmacro.nim");
				LOC24 = (Exception*)0;
				LOC24 = getCurrentException();
				fail_ItRyHxJqOxe7y9cEgBvDaow((*HEX3Aenvp_9c0mKMU5cZDlDz1SKPE9an9aw).retfuture214435, LOC24);
			}
			LA19: ;
			popCurrentException();
		}
	}
	if (T_Y4ea819azvvYDURtHxhdboQ_21.status != 0) reraiseException();
	popFrame();
}

N_NIMCALL(FutureHEX3Aobjecttype_bl7bh8u9cSFPi08mZFnBBvg*, serve_RG4z1DHEHLjhFTrGU2RsHA)(void) {
	FutureHEX3Aobjecttype_bl7bh8u9cSFPi08mZFnBBvg* result0;
	EnvlibHEX2FpureHEX2FasyncmacroHEX2Enim319_OF4bTGyWWMUcvP6Zm2bvKA* HEX3Aenv_6sHKthE29c12KcsqF9cvdYUg;
	EnvlibHEX2FpureHEX2FasyncmacroHEX2Enim337_h9bthBHwOfI2F06jOR8qr0w* HEX3Aenv_6sHKthE29c12KcsqF9cvdYUg_2;
	TY_hMF8LVJgm4deTaCKWP1jCg LOC1;
	TY_IIomJ6ptE6vfJ5zRbATgkQ LOC2;
	nimfr("serve", "chat.nim")
{	result0 = (FutureHEX3Aobjecttype_bl7bh8u9cSFPi08mZFnBBvg*)0;
	HEX3Aenv_6sHKthE29c12KcsqF9cvdYUg = (EnvlibHEX2FpureHEX2FasyncmacroHEX2Enim319_OF4bTGyWWMUcvP6Zm2bvKA*)0;
	nimln(15, "chat.nim");
	HEX3Aenv_6sHKthE29c12KcsqF9cvdYUg = (EnvlibHEX2FpureHEX2FasyncmacroHEX2Enim319_OF4bTGyWWMUcvP6Zm2bvKA*) newObj((&NTI_uAN6f0WUvo8vegDEgsMB3g), sizeof(EnvlibHEX2FpureHEX2FasyncmacroHEX2Enim319_OF4bTGyWWMUcvP6Zm2bvKA));
	asgnRef((void**) (&(*HEX3Aenv_6sHKthE29c12KcsqF9cvdYUg).retfuture214435), newfuture_G3cvvvURs8ow9aoa6g18ncw(((NimStringDesc*) &T_Y4ea819azvvYDURtHxhdboQ_18)));
	nimln(29, "asyncmacro.nim");
	HEX3Aenv_6sHKthE29c12KcsqF9cvdYUg_2 = (EnvlibHEX2FpureHEX2FasyncmacroHEX2Enim337_h9bthBHwOfI2F06jOR8qr0w*)0;
	nimln(337, "asyncmacro.nim");
	HEX3Aenv_6sHKthE29c12KcsqF9cvdYUg_2 = (EnvlibHEX2FpureHEX2FasyncmacroHEX2Enim337_h9bthBHwOfI2F06jOR8qr0w*) newObj((&NTI_v6ASVpxlmOrrc9cXv9bnJfsA), sizeof(EnvlibHEX2FpureHEX2FasyncmacroHEX2Enim337_h9bthBHwOfI2F06jOR8qr0w));
	asgnRef((void**) (&(*HEX3Aenv_6sHKthE29c12KcsqF9cvdYUg_2).HEX3Aup), HEX3Aenv_6sHKthE29c12KcsqF9cvdYUg);
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.ClPrc = serveiter_FwpCqkh4zoF81ZW59byNp0A_2; LOC1.ClEnv = HEX3Aenv_6sHKthE29c12KcsqF9cvdYUg_2;
	asgnRef((void**) (&(*HEX3Aenv_6sHKthE29c12KcsqF9cvdYUg).nameitervar214439.ClEnv), LOC1.ClEnv);
	(*HEX3Aenv_6sHKthE29c12KcsqF9cvdYUg).nameitervar214439.ClPrc = LOC1.ClPrc;
	nimln(370, "asyncmacro.nim");
	memset((void*)(&LOC2), 0, sizeof(LOC2));
	LOC2.ClPrc = cb_5iL7T2rlB1M5Gwameo3UlA_2; LOC2.ClEnv = HEX3Aenv_6sHKthE29c12KcsqF9cvdYUg;
	LOC2.ClEnv? LOC2.ClPrc(LOC2.ClEnv):((T_Y4ea819azvvYDURtHxhdboQ_24)(LOC2.ClPrc))();
	nimln(16, "chat.nim");
	nimln(319, "asyncmacro.nim");
	result0 = (*HEX3Aenv_6sHKthE29c12KcsqF9cvdYUg).retfuture214435;
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result0;
}

static N_INLINE(void, initStackBottomWith)(void* locals0) {
	setStackBottom(locals0);
}
void PreMainInner() {
	systemInit000();
	stdlib_parseutilsDatInit000();
	stdlib_mathDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_timesDatInit000();
	stdlib_posixDatInit000();
	stdlib_osDatInit000();
	stdlib_endiansDatInit000();
	stdlib_oidsDatInit000();
	stdlib_etcprivDatInit000();
	stdlib_hashesDatInit000();
	stdlib_tablesDatInit000();
	stdlib_heapqueueDatInit000();
	stdlib_nativesocketsDatInit000();
	stdlib_setsDatInit000();
	stdlib_netDatInit000();
	stdlib_dequesDatInit000();
	stdlib_kqueueDatInit000();
	stdlib_selectorsDatInit000();
	stdlib_macrosDatInit000();
	stdlib_asyncdispatchDatInit000();
	stdlib_asyncnetDatInit000();
	chatDatInit000();
	stdlib_parseutilsInit000();
	stdlib_mathInit000();
	stdlib_algorithmInit000();
	stdlib_strutilsInit000();
	stdlib_timesInit000();
	stdlib_posixInit000();
	stdlib_osInit000();
	stdlib_endiansInit000();
	stdlib_oidsInit000();
	stdlib_etcprivInit000();
	stdlib_hashesInit000();
	stdlib_tablesInit000();
	stdlib_heapqueueInit000();
	stdlib_nativesocketsInit000();
	stdlib_setsInit000();
	stdlib_netInit000();
	stdlib_dequesInit000();
	stdlib_kqueueInit000();
	stdlib_selectorsInit000();
	stdlib_macrosInit000();
	stdlib_asyncdispatchInit000();
	stdlib_asyncnetInit000();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	FutureHEX3Aobjecttype_bl7bh8u9cSFPi08mZFnBBvg* LOC1;
	nimfr("chat", "chat.nim")
nimRegisterGlobalMarker(T_Y4ea819azvvYDURtHxhdboQ_2);
	nimln(28, "chat.nim");
	LOC1 = (FutureHEX3Aobjecttype_bl7bh8u9cSFPi08mZFnBBvg*)0;
	LOC1 = serve_RG4z1DHEHLjhFTrGU2RsHA();
	asynccheck_WahSjU7mz9cy8hV9aDbOumwQ_3(LOC1);
	nimln(29, "chat.nim");
	runforever_jSFKlHW9aWQ06mz9a6ZF5Ylw();
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, chatDatInit000)(void) {
static TNimNode* T_Y4ea819azvvYDURtHxhdboQ_6[4];
static TNimNode* T_Y4ea819azvvYDURtHxhdboQ_8[9];
static TNimNode* T_Y4ea819azvvYDURtHxhdboQ_17[3];
static TNimNode* T_Y4ea819azvvYDURtHxhdboQ_19[5];
static TNimNode T_Y4ea819azvvYDURtHxhdboQ_0[25];
NTI_r7PmaaK9bk3N2VzaDu0773g.size = sizeof(TY_r7PmaaK9bk3N2VzaDu0773g*);
NTI_r7PmaaK9bk3N2VzaDu0773g.kind = 24;
NTI_r7PmaaK9bk3N2VzaDu0773g.base = (&NTI_aSlRc15aht0VRnOJAwHxLg);
NTI_r7PmaaK9bk3N2VzaDu0773g.flags = 2;
NTI_r7PmaaK9bk3N2VzaDu0773g.marker = Marker_TY_r7PmaaK9bk3N2VzaDu0773g;
NTI_9cLknjWm8y9bzwHE4y0Fkp8A.size = sizeof(EnvchatHEX2Enim6_9cLknjWm8y9bzwHE4y0Fkp8A);
NTI_9cLknjWm8y9bzwHE4y0Fkp8A.kind = 18;
NTI_9cLknjWm8y9bzwHE4y0Fkp8A.base = 0;
T_Y4ea819azvvYDURtHxhdboQ_6[0] = &T_Y4ea819azvvYDURtHxhdboQ_0[1];
T_Y4ea819azvvYDURtHxhdboQ_0[1].kind = 1;
T_Y4ea819azvvYDURtHxhdboQ_0[1].offset = offsetof(EnvchatHEX2Enim6_9cLknjWm8y9bzwHE4y0Fkp8A, HEX3Astate);
T_Y4ea819azvvYDURtHxhdboQ_0[1].typ = (&NTI_xHTZrq9aYs6boc9bCba0JbpQ);
T_Y4ea819azvvYDURtHxhdboQ_0[1].name = ":state";
T_Y4ea819azvvYDURtHxhdboQ_6[1] = &T_Y4ea819azvvYDURtHxhdboQ_0[2];
T_Y4ea819azvvYDURtHxhdboQ_0[2].kind = 1;
T_Y4ea819azvvYDURtHxhdboQ_0[2].offset = offsetof(EnvchatHEX2Enim6_9cLknjWm8y9bzwHE4y0Fkp8A, client214015);
T_Y4ea819azvvYDURtHxhdboQ_0[2].typ = (&NTI_aSlRc15aht0VRnOJAwHxLg);
T_Y4ea819azvvYDURtHxhdboQ_0[2].name = "client214015";
T_Y4ea819azvvYDURtHxhdboQ_6[2] = &T_Y4ea819azvvYDURtHxhdboQ_0[3];
T_Y4ea819azvvYDURtHxhdboQ_0[3].kind = 1;
T_Y4ea819azvvYDURtHxhdboQ_0[3].offset = offsetof(EnvchatHEX2Enim6_9cLknjWm8y9bzwHE4y0Fkp8A, retfuture214004);
T_Y4ea819azvvYDURtHxhdboQ_0[3].typ = (&NTI_Iud5eP9cpfQsJ8yP1cJOApw);
T_Y4ea819azvvYDURtHxhdboQ_0[3].name = "retFuture214004";
T_Y4ea819azvvYDURtHxhdboQ_6[3] = &T_Y4ea819azvvYDURtHxhdboQ_0[4];
T_Y4ea819azvvYDURtHxhdboQ_0[4].kind = 1;
T_Y4ea819azvvYDURtHxhdboQ_0[4].offset = offsetof(EnvchatHEX2Enim6_9cLknjWm8y9bzwHE4y0Fkp8A, nameitervar214010);
T_Y4ea819azvvYDURtHxhdboQ_0[4].typ = (&NTI_hMF8LVJgm4deTaCKWP1jCg);
T_Y4ea819azvvYDURtHxhdboQ_0[4].name = "nameIterVar214010";
T_Y4ea819azvvYDURtHxhdboQ_0[0].len = 4; T_Y4ea819azvvYDURtHxhdboQ_0[0].kind = 2; T_Y4ea819azvvYDURtHxhdboQ_0[0].sons = &T_Y4ea819azvvYDURtHxhdboQ_6[0];
NTI_9cLknjWm8y9bzwHE4y0Fkp8A.node = &T_Y4ea819azvvYDURtHxhdboQ_0[0];
NTI_Fko9cV1i9bRpBx9cYeen2ILOQ.size = sizeof(EnvchatHEX2Enim6_9cLknjWm8y9bzwHE4y0Fkp8A*);
NTI_Fko9cV1i9bRpBx9cYeen2ILOQ.kind = 22;
NTI_Fko9cV1i9bRpBx9cYeen2ILOQ.base = (&NTI_9cLknjWm8y9bzwHE4y0Fkp8A);
NTI_Fko9cV1i9bRpBx9cYeen2ILOQ.marker = Marker_TY_Fko9cV1i9bRpBx9cYeen2ILOQ;
NTI_xFNmcra4Uj4tX9a7gFBd4mA.size = sizeof(EnvlibHEX2FpureHEX2FasyncmacroHEX2Enim337_xFNmcra4Uj4tX9a7gFBd4mA);
NTI_xFNmcra4Uj4tX9a7gFBd4mA.kind = 18;
NTI_xFNmcra4Uj4tX9a7gFBd4mA.base = 0;
T_Y4ea819azvvYDURtHxhdboQ_8[0] = &T_Y4ea819azvvYDURtHxhdboQ_0[6];
T_Y4ea819azvvYDURtHxhdboQ_0[6].kind = 1;
T_Y4ea819azvvYDURtHxhdboQ_0[6].offset = offsetof(EnvlibHEX2FpureHEX2FasyncmacroHEX2Enim337_xFNmcra4Uj4tX9a7gFBd4mA, HEX3Astate);
T_Y4ea819azvvYDURtHxhdboQ_0[6].typ = (&NTI_n4zDRFGzCsBJcFgUikBMgw);
T_Y4ea819azvvYDURtHxhdboQ_0[6].name = ":state";
T_Y4ea819azvvYDURtHxhdboQ_8[1] = &T_Y4ea819azvvYDURtHxhdboQ_0[7];
T_Y4ea819azvvYDURtHxhdboQ_0[7].kind = 1;
T_Y4ea819azvvYDURtHxhdboQ_0[7].offset = offsetof(EnvlibHEX2FpureHEX2FasyncmacroHEX2Enim337_xFNmcra4Uj4tX9a7gFBd4mA, future214006);
T_Y4ea819azvvYDURtHxhdboQ_0[7].typ = (&NTI_Iud5eP9cpfQsJ8yP1cJOApw);
T_Y4ea819azvvYDURtHxhdboQ_0[7].name = "future214006";
T_Y4ea819azvvYDURtHxhdboQ_8[2] = &T_Y4ea819azvvYDURtHxhdboQ_0[8];
T_Y4ea819azvvYDURtHxhdboQ_0[8].kind = 1;
T_Y4ea819azvvYDURtHxhdboQ_0[8].offset = offsetof(EnvlibHEX2FpureHEX2FasyncmacroHEX2Enim337_xFNmcra4Uj4tX9a7gFBd4mA, HEX3Aup);
T_Y4ea819azvvYDURtHxhdboQ_0[8].typ = (&NTI_Fko9cV1i9bRpBx9cYeen2ILOQ);
T_Y4ea819azvvYDURtHxhdboQ_0[8].name = ":up";
T_Y4ea819azvvYDURtHxhdboQ_8[3] = &T_Y4ea819azvvYDURtHxhdboQ_0[9];
T_Y4ea819azvvYDURtHxhdboQ_0[9].kind = 1;
T_Y4ea819azvvYDURtHxhdboQ_0[9].offset = offsetof(EnvlibHEX2FpureHEX2FasyncmacroHEX2Enim337_xFNmcra4Uj4tX9a7gFBd4mA, future214007);
T_Y4ea819azvvYDURtHxhdboQ_0[9].typ = (&NTI_zlVC9ci9cgyDtfEw4KbxcACA);
T_Y4ea819azvvYDURtHxhdboQ_0[9].name = "future214007";
T_Y4ea819azvvYDURtHxhdboQ_8[4] = &T_Y4ea819azvvYDURtHxhdboQ_0[10];
T_Y4ea819azvvYDURtHxhdboQ_0[10].kind = 1;
T_Y4ea819azvvYDURtHxhdboQ_0[10].offset = offsetof(EnvlibHEX2FpureHEX2FasyncmacroHEX2Enim337_xFNmcra4Uj4tX9a7gFBd4mA, line214246);
T_Y4ea819azvvYDURtHxhdboQ_0[10].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg);
T_Y4ea819azvvYDURtHxhdboQ_0[10].name = "line214246";
T_Y4ea819azvvYDURtHxhdboQ_8[5] = &T_Y4ea819azvvYDURtHxhdboQ_0[11];
T_Y4ea819azvvYDURtHxhdboQ_0[11].kind = 1;
T_Y4ea819azvvYDURtHxhdboQ_0[11].offset = offsetof(EnvlibHEX2FpureHEX2FasyncmacroHEX2Enim337_xFNmcra4Uj4tX9a7gFBd4mA, c214255);
T_Y4ea819azvvYDURtHxhdboQ_0[11].typ = (&NTI_aSlRc15aht0VRnOJAwHxLg);
T_Y4ea819azvvYDURtHxhdboQ_0[11].name = "c214255";
T_Y4ea819azvvYDURtHxhdboQ_8[6] = &T_Y4ea819azvvYDURtHxhdboQ_0[12];
T_Y4ea819azvvYDURtHxhdboQ_0[12].kind = 1;
T_Y4ea819azvvYDURtHxhdboQ_0[12].offset = offsetof(EnvlibHEX2FpureHEX2FasyncmacroHEX2Enim337_xFNmcra4Uj4tX9a7gFBd4mA, i214290);
T_Y4ea819azvvYDURtHxhdboQ_0[12].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA);
T_Y4ea819azvvYDURtHxhdboQ_0[12].name = "i214290";
T_Y4ea819azvvYDURtHxhdboQ_8[7] = &T_Y4ea819azvvYDURtHxhdboQ_0[13];
T_Y4ea819azvvYDURtHxhdboQ_0[13].kind = 1;
T_Y4ea819azvvYDURtHxhdboQ_0[13].offset = offsetof(EnvlibHEX2FpureHEX2FasyncmacroHEX2Enim337_xFNmcra4Uj4tX9a7gFBd4mA, L214292);
T_Y4ea819azvvYDURtHxhdboQ_0[13].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA);
T_Y4ea819azvvYDURtHxhdboQ_0[13].name = "L214292";
T_Y4ea819azvvYDURtHxhdboQ_8[8] = &T_Y4ea819azvvYDURtHxhdboQ_0[14];
T_Y4ea819azvvYDURtHxhdboQ_0[14].kind = 1;
T_Y4ea819azvvYDURtHxhdboQ_0[14].offset = offsetof(EnvlibHEX2FpureHEX2FasyncmacroHEX2Enim337_xFNmcra4Uj4tX9a7gFBd4mA, future214008);
T_Y4ea819azvvYDURtHxhdboQ_0[14].typ = (&NTI_Iud5eP9cpfQsJ8yP1cJOApw);
T_Y4ea819azvvYDURtHxhdboQ_0[14].name = "future214008";
T_Y4ea819azvvYDURtHxhdboQ_0[5].len = 9; T_Y4ea819azvvYDURtHxhdboQ_0[5].kind = 2; T_Y4ea819azvvYDURtHxhdboQ_0[5].sons = &T_Y4ea819azvvYDURtHxhdboQ_8[0];
NTI_xFNmcra4Uj4tX9a7gFBd4mA.node = &T_Y4ea819azvvYDURtHxhdboQ_0[5];
NTI_3AX0CJo9anifpFy9aVSHPYXg.size = sizeof(EnvlibHEX2FpureHEX2FasyncmacroHEX2Enim337_xFNmcra4Uj4tX9a7gFBd4mA*);
NTI_3AX0CJo9anifpFy9aVSHPYXg.kind = 22;
NTI_3AX0CJo9anifpFy9aVSHPYXg.base = (&NTI_xFNmcra4Uj4tX9a7gFBd4mA);
NTI_3AX0CJo9anifpFy9aVSHPYXg.marker = Marker_TY_3AX0CJo9anifpFy9aVSHPYXg;
NTI_OF4bTGyWWMUcvP6Zm2bvKA.size = sizeof(EnvlibHEX2FpureHEX2FasyncmacroHEX2Enim319_OF4bTGyWWMUcvP6Zm2bvKA);
NTI_OF4bTGyWWMUcvP6Zm2bvKA.kind = 18;
NTI_OF4bTGyWWMUcvP6Zm2bvKA.base = 0;
T_Y4ea819azvvYDURtHxhdboQ_17[0] = &T_Y4ea819azvvYDURtHxhdboQ_0[16];
T_Y4ea819azvvYDURtHxhdboQ_0[16].kind = 1;
T_Y4ea819azvvYDURtHxhdboQ_0[16].offset = offsetof(EnvlibHEX2FpureHEX2FasyncmacroHEX2Enim319_OF4bTGyWWMUcvP6Zm2bvKA, HEX3Astate);
T_Y4ea819azvvYDURtHxhdboQ_0[16].typ = (&NTI_xHTZrq9aYs6boc9bCba0JbpQ);
T_Y4ea819azvvYDURtHxhdboQ_0[16].name = ":state";
T_Y4ea819azvvYDURtHxhdboQ_17[1] = &T_Y4ea819azvvYDURtHxhdboQ_0[17];
T_Y4ea819azvvYDURtHxhdboQ_0[17].kind = 1;
T_Y4ea819azvvYDURtHxhdboQ_0[17].offset = offsetof(EnvlibHEX2FpureHEX2FasyncmacroHEX2Enim319_OF4bTGyWWMUcvP6Zm2bvKA, retfuture214435);
T_Y4ea819azvvYDURtHxhdboQ_0[17].typ = (&NTI_Iud5eP9cpfQsJ8yP1cJOApw);
T_Y4ea819azvvYDURtHxhdboQ_0[17].name = "retFuture214435";
T_Y4ea819azvvYDURtHxhdboQ_17[2] = &T_Y4ea819azvvYDURtHxhdboQ_0[18];
T_Y4ea819azvvYDURtHxhdboQ_0[18].kind = 1;
T_Y4ea819azvvYDURtHxhdboQ_0[18].offset = offsetof(EnvlibHEX2FpureHEX2FasyncmacroHEX2Enim319_OF4bTGyWWMUcvP6Zm2bvKA, nameitervar214439);
T_Y4ea819azvvYDURtHxhdboQ_0[18].typ = (&NTI_hMF8LVJgm4deTaCKWP1jCg);
T_Y4ea819azvvYDURtHxhdboQ_0[18].name = "nameIterVar214439";
T_Y4ea819azvvYDURtHxhdboQ_0[15].len = 3; T_Y4ea819azvvYDURtHxhdboQ_0[15].kind = 2; T_Y4ea819azvvYDURtHxhdboQ_0[15].sons = &T_Y4ea819azvvYDURtHxhdboQ_17[0];
NTI_OF4bTGyWWMUcvP6Zm2bvKA.node = &T_Y4ea819azvvYDURtHxhdboQ_0[15];
NTI_uAN6f0WUvo8vegDEgsMB3g.size = sizeof(EnvlibHEX2FpureHEX2FasyncmacroHEX2Enim319_OF4bTGyWWMUcvP6Zm2bvKA*);
NTI_uAN6f0WUvo8vegDEgsMB3g.kind = 22;
NTI_uAN6f0WUvo8vegDEgsMB3g.base = (&NTI_OF4bTGyWWMUcvP6Zm2bvKA);
NTI_uAN6f0WUvo8vegDEgsMB3g.marker = Marker_TY_uAN6f0WUvo8vegDEgsMB3g;
NTI_h9bthBHwOfI2F06jOR8qr0w.size = sizeof(EnvlibHEX2FpureHEX2FasyncmacroHEX2Enim337_h9bthBHwOfI2F06jOR8qr0w);
NTI_h9bthBHwOfI2F06jOR8qr0w.kind = 18;
NTI_h9bthBHwOfI2F06jOR8qr0w.base = 0;
T_Y4ea819azvvYDURtHxhdboQ_19[0] = &T_Y4ea819azvvYDURtHxhdboQ_0[20];
T_Y4ea819azvvYDURtHxhdboQ_0[20].kind = 1;
T_Y4ea819azvvYDURtHxhdboQ_0[20].offset = offsetof(EnvlibHEX2FpureHEX2FasyncmacroHEX2Enim337_h9bthBHwOfI2F06jOR8qr0w, HEX3Astate);
T_Y4ea819azvvYDURtHxhdboQ_0[20].typ = (&NTI_Mpt8aZ13tT2AYV71yyfHcA);
T_Y4ea819azvvYDURtHxhdboQ_0[20].name = ":state";
T_Y4ea819azvvYDURtHxhdboQ_19[1] = &T_Y4ea819azvvYDURtHxhdboQ_0[21];
T_Y4ea819azvvYDURtHxhdboQ_0[21].kind = 1;
T_Y4ea819azvvYDURtHxhdboQ_0[21].offset = offsetof(EnvlibHEX2FpureHEX2FasyncmacroHEX2Enim337_h9bthBHwOfI2F06jOR8qr0w, server214473);
T_Y4ea819azvvYDURtHxhdboQ_0[21].typ = (&NTI_aSlRc15aht0VRnOJAwHxLg);
T_Y4ea819azvvYDURtHxhdboQ_0[21].name = "server214473";
T_Y4ea819azvvYDURtHxhdboQ_19[2] = &T_Y4ea819azvvYDURtHxhdboQ_0[22];
T_Y4ea819azvvYDURtHxhdboQ_0[22].kind = 1;
T_Y4ea819azvvYDURtHxhdboQ_0[22].offset = offsetof(EnvlibHEX2FpureHEX2FasyncmacroHEX2Enim337_h9bthBHwOfI2F06jOR8qr0w, future214437);
T_Y4ea819azvvYDURtHxhdboQ_0[22].typ = (&NTI_QXDs9ajrOVAncGNEc54sO3g);
T_Y4ea819azvvYDURtHxhdboQ_0[22].name = "future214437";
T_Y4ea819azvvYDURtHxhdboQ_19[3] = &T_Y4ea819azvvYDURtHxhdboQ_0[23];
T_Y4ea819azvvYDURtHxhdboQ_0[23].kind = 1;
T_Y4ea819azvvYDURtHxhdboQ_0[23].offset = offsetof(EnvlibHEX2FpureHEX2FasyncmacroHEX2Enim337_h9bthBHwOfI2F06jOR8qr0w, client214814);
T_Y4ea819azvvYDURtHxhdboQ_0[23].typ = (&NTI_aSlRc15aht0VRnOJAwHxLg);
T_Y4ea819azvvYDURtHxhdboQ_0[23].name = "client214814";
T_Y4ea819azvvYDURtHxhdboQ_19[4] = &T_Y4ea819azvvYDURtHxhdboQ_0[24];
T_Y4ea819azvvYDURtHxhdboQ_0[24].kind = 1;
T_Y4ea819azvvYDURtHxhdboQ_0[24].offset = offsetof(EnvlibHEX2FpureHEX2FasyncmacroHEX2Enim337_h9bthBHwOfI2F06jOR8qr0w, HEX3Aup);
T_Y4ea819azvvYDURtHxhdboQ_0[24].typ = (&NTI_uAN6f0WUvo8vegDEgsMB3g);
T_Y4ea819azvvYDURtHxhdboQ_0[24].name = ":up";
T_Y4ea819azvvYDURtHxhdboQ_0[19].len = 5; T_Y4ea819azvvYDURtHxhdboQ_0[19].kind = 2; T_Y4ea819azvvYDURtHxhdboQ_0[19].sons = &T_Y4ea819azvvYDURtHxhdboQ_19[0];
NTI_h9bthBHwOfI2F06jOR8qr0w.node = &T_Y4ea819azvvYDURtHxhdboQ_0[19];
NTI_v6ASVpxlmOrrc9cXv9bnJfsA.size = sizeof(EnvlibHEX2FpureHEX2FasyncmacroHEX2Enim337_h9bthBHwOfI2F06jOR8qr0w*);
NTI_v6ASVpxlmOrrc9cXv9bnJfsA.kind = 22;
NTI_v6ASVpxlmOrrc9cXv9bnJfsA.base = (&NTI_h9bthBHwOfI2F06jOR8qr0w);
NTI_v6ASVpxlmOrrc9cXv9bnJfsA.marker = Marker_TY_v6ASVpxlmOrrc9cXv9bnJfsA;
}

