/* Generated by Nim Compiler v0.16.0 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/usr/local/Cellar/nim/0.16.0/nim/lib -o /Users/jack.sarick/Desktop/land_of_nim/nimcache/stdlib_kqueue.o /Users/jack.sarick/Desktop/land_of_nim/nimcache/stdlib_kqueue.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <sys/types.h>
                       #include <sys/event.h>
                       #include <sys/time.h>
#undef linux
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef NU8 Tnimkind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 Tnimtypeflag_v8QUszD1sWlSIWZz7mC4bQ_Set;
typedef N_NIMCALL_PTR(void, TY_ojoeKfW4VYIm36I9cpDTQIg) (void* p0, NI op0);
typedef N_NIMCALL_PTR(void*, TY_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p0);
struct  TNimType  {
NI size;
Tnimkind_jIBKr1ejBgsfM33Kxw4j7A kind;
Tnimtypeflag_v8QUszD1sWlSIWZz7mC4bQ_Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY_ojoeKfW4VYIm36I9cpDTQIg marker;
TY_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 Tnimnodekind_unfNsxrcATrufDZmpBq4HQ;
struct  TNimNode  {
Tnimnodekind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
static N_INLINE(void, nimFrame)(TFrame* s0);
N_NOINLINE(void, stackoverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
TNimType NTI_9cG9coEVt8bUEuxUupPPZigQ;
extern TNimType NTI_hMQEc0FMry7Up7EoPki79aA;
extern TNimType NTI_Je1oecM0CZvYjDOZmWnK7A;
extern TNimType NTI_Ld4tGHXm9a29c6JIT1D6B7Fw;
extern TNimType NTI_EfDYb5NOiMBijiUDCmXqPw;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA;
extern TNimType NTI_vr5DoT1jILTGdRlYv1OYpw;
extern TFrame* frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw;

static N_INLINE(void, nimFrame)(TFrame* s0) {
	NI LOC1;
	LOC1 = (NI)0;
	{
		if (!(frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s0).calldepth = ((NI16) (LOC1));
	(*s0).prev = frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw = s0;
	{
		if (!((*s0).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_kqueueInit000)(void) {
	nimfr("kqueue", "kqueue.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_kqueueDatInit000)(void) {
static TNimNode* T_1kzqA9bW2HHqj6lSbci9cdZg_2[6];
static TNimNode T_1kzqA9bW2HHqj6lSbci9cdZg_0[7];
NTI_9cG9coEVt8bUEuxUupPPZigQ.size = sizeof(struct kevent);
NTI_9cG9coEVt8bUEuxUupPPZigQ.kind = 18;
NTI_9cG9coEVt8bUEuxUupPPZigQ.base = 0;
NTI_9cG9coEVt8bUEuxUupPPZigQ.flags = 3;
T_1kzqA9bW2HHqj6lSbci9cdZg_2[0] = &T_1kzqA9bW2HHqj6lSbci9cdZg_0[1];
T_1kzqA9bW2HHqj6lSbci9cdZg_0[1].kind = 1;
T_1kzqA9bW2HHqj6lSbci9cdZg_0[1].offset = offsetof(struct kevent, ident);
T_1kzqA9bW2HHqj6lSbci9cdZg_0[1].typ = (&NTI_hMQEc0FMry7Up7EoPki79aA);
T_1kzqA9bW2HHqj6lSbci9cdZg_0[1].name = "ident";
T_1kzqA9bW2HHqj6lSbci9cdZg_2[1] = &T_1kzqA9bW2HHqj6lSbci9cdZg_0[2];
T_1kzqA9bW2HHqj6lSbci9cdZg_0[2].kind = 1;
T_1kzqA9bW2HHqj6lSbci9cdZg_0[2].offset = offsetof(struct kevent, filter);
T_1kzqA9bW2HHqj6lSbci9cdZg_0[2].typ = (&NTI_Je1oecM0CZvYjDOZmWnK7A);
T_1kzqA9bW2HHqj6lSbci9cdZg_0[2].name = "filter";
T_1kzqA9bW2HHqj6lSbci9cdZg_2[2] = &T_1kzqA9bW2HHqj6lSbci9cdZg_0[3];
T_1kzqA9bW2HHqj6lSbci9cdZg_0[3].kind = 1;
T_1kzqA9bW2HHqj6lSbci9cdZg_0[3].offset = offsetof(struct kevent, flags);
T_1kzqA9bW2HHqj6lSbci9cdZg_0[3].typ = (&NTI_Ld4tGHXm9a29c6JIT1D6B7Fw);
T_1kzqA9bW2HHqj6lSbci9cdZg_0[3].name = "flags";
T_1kzqA9bW2HHqj6lSbci9cdZg_2[3] = &T_1kzqA9bW2HHqj6lSbci9cdZg_0[4];
T_1kzqA9bW2HHqj6lSbci9cdZg_0[4].kind = 1;
T_1kzqA9bW2HHqj6lSbci9cdZg_0[4].offset = offsetof(struct kevent, fflags);
T_1kzqA9bW2HHqj6lSbci9cdZg_0[4].typ = (&NTI_EfDYb5NOiMBijiUDCmXqPw);
T_1kzqA9bW2HHqj6lSbci9cdZg_0[4].name = "fflags";
T_1kzqA9bW2HHqj6lSbci9cdZg_2[4] = &T_1kzqA9bW2HHqj6lSbci9cdZg_0[5];
T_1kzqA9bW2HHqj6lSbci9cdZg_0[5].kind = 1;
T_1kzqA9bW2HHqj6lSbci9cdZg_0[5].offset = offsetof(struct kevent, data);
T_1kzqA9bW2HHqj6lSbci9cdZg_0[5].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA);
T_1kzqA9bW2HHqj6lSbci9cdZg_0[5].name = "data";
T_1kzqA9bW2HHqj6lSbci9cdZg_2[5] = &T_1kzqA9bW2HHqj6lSbci9cdZg_0[6];
T_1kzqA9bW2HHqj6lSbci9cdZg_0[6].kind = 1;
T_1kzqA9bW2HHqj6lSbci9cdZg_0[6].offset = offsetof(struct kevent, udata);
T_1kzqA9bW2HHqj6lSbci9cdZg_0[6].typ = (&NTI_vr5DoT1jILTGdRlYv1OYpw);
T_1kzqA9bW2HHqj6lSbci9cdZg_0[6].name = "udata";
T_1kzqA9bW2HHqj6lSbci9cdZg_0[0].len = 6; T_1kzqA9bW2HHqj6lSbci9cdZg_0[0].kind = 2; T_1kzqA9bW2HHqj6lSbci9cdZg_0[0].sons = &T_1kzqA9bW2HHqj6lSbci9cdZg_2[0];
NTI_9cG9coEVt8bUEuxUupPPZigQ.node = &T_1kzqA9bW2HHqj6lSbci9cdZg_0[0];
}

