/* Generated by Nim Compiler v0.16.0 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/usr/local/Cellar/nim/0.16.0/nim/lib -o /Users/jack.sarick/Desktop/land_of_nim/nimcache/stdlib_selectors.o /Users/jack.sarick/Desktop/land_of_nim/nimcache/stdlib_selectors.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <sys/types.h>
                       #include <sys/event.h>
                       #include <sys/time.h>
#include <string.h>
#include <sys/event.h>
#include <unistd.h>
#include <time.h>
#include <errno.h>
#undef linux
typedef struct Table_bnna5wr180tUeaeDFxJ4xA Table_bnna5wr180tUeaeDFxJ4xA;
typedef struct Selectorkey_gE60aCfYXV1Nf1VTfPbepw Selectorkey_gE60aCfYXV1Nf1VTfPbepw;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct TY_wQibBbBZLWmdoNxHgCZRyw TY_wQibBbBZLWmdoNxHgCZRyw;
typedef struct TY_ponAwt7gy9asnIS681IafZQ TY_ponAwt7gy9asnIS681IafZQ;
typedef struct Selector_X89cGFWVbzYzXTnuQzGngmA Selector_X89cGFWVbzYzXTnuQzGngmA;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TY_bkMUR8maranmy38dEG39cHA TY_bkMUR8maranmy38dEG39cHA;
typedef struct TY_nEEz1gjcivYloysklmeNTg TY_nEEz1gjcivYloysklmeNTg;
typedef struct Cell_1zcF9cV8XIAtbN8h5HRUB8g Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct Cellseq_Axo1XVm9aaQueTOldv8le5w Cellseq_Axo1XVm9aaQueTOldv8le5w;
typedef struct Gcheap_1TRH1TZMaVZTnLNcIHuNFQ Gcheap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct Gcstack_7fytPA5bBsob6See21YMRA Gcstack_7fytPA5bBsob6See21YMRA;
typedef struct Memregion_x81NhDv59b8ercDZ9bi85jyg Memregion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct Smallchunk_tXn60W2f8h3jgAYdEmy5NQ Smallchunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct Llchunk_XsENErzHIZV9bhvyJx56wGw Llchunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct Bigchunk_Rv9c70Uhp2TytkX7eH78qEg Bigchunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct Intset_EZObFrE3NC9bIb3YMkY9crZA Intset_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct Trunk_W0r8S0Y3UGke6T9bIUWnnuw Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct Avlnode_IaqjtwKhxLEpvDS9bct9blEw Avlnode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct Gcstat_0RwLoVBHZPfUAcLczmfQAg Gcstat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct Cellset_jG87P0AI9aZtss9ccTYBIISQ Cellset_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct Pagedesc_fublkgIY4LG3mT51LU2WHg Pagedesc_fublkgIY4LG3mT51LU2WHg;
typedef struct Basechunk_Sdq7WpT6qAH858F5ZEdG3w Basechunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct Freecell_u6M5LHprqzkn9axr04yg9bGQ Freecell_u6M5LHprqzkn9axr04yg9bGQ;
typedef NU8 Event_nI40bZzTyYVrl763dZ9aHDg_Set;
struct  Selectorkey_gE60aCfYXV1Nf1VTfPbepw  {
int fd;
Event_nI40bZzTyYVrl763dZ9aHDg_Set events;
TNimObject* data;
};
typedef NU8 Tnimkind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 Tnimtypeflag_v8QUszD1sWlSIWZz7mC4bQ_Set;
typedef N_NIMCALL_PTR(void, TY_ojoeKfW4VYIm36I9cpDTQIg) (void* p0, NI op0);
typedef N_NIMCALL_PTR(void*, TY_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p0);
struct  TNimType  {
NI size;
Tnimkind_jIBKr1ejBgsfM33Kxw4j7A kind;
Tnimtypeflag_v8QUszD1sWlSIWZz7mC4bQ_Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY_ojoeKfW4VYIm36I9cpDTQIg marker;
TY_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 Tnimnodekind_unfNsxrcATrufDZmpBq4HQ;
struct  TNimNode  {
Tnimnodekind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef NU8 Event_nI40bZzTyYVrl763dZ9aHDg;
struct  Table_bnna5wr180tUeaeDFxJ4xA  {
TY_wQibBbBZLWmdoNxHgCZRyw* data;
NI counter;
};
struct TY_ponAwt7gy9asnIS681IafZQ {
NI Field0;
int Field1;
Selectorkey_gE60aCfYXV1Nf1VTfPbepw Field2;
};
typedef struct kevent TY_80NdCG41SyhPocFo20IbDw[64];
struct  Selector_X89cGFWVbzYzXTnuQzGngmA  {
int kqfd;
TY_80NdCG41SyhPocFo20IbDw events;
Table_bnna5wr180tUeaeDFxJ4xA fds;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct TY_nEEz1gjcivYloysklmeNTg {
Selectorkey_gE60aCfYXV1Nf1VTfPbepw Field0;
Event_nI40bZzTyYVrl763dZ9aHDg_Set Field1;
};
struct  Cell_1zcF9cV8XIAtbN8h5HRUB8g  {
NI refcount;
TNimType* typ;
};
struct  Cellseq_Axo1XVm9aaQueTOldv8le5w  {
NI len;
NI cap;
Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef Smallchunk_tXn60W2f8h3jgAYdEmy5NQ* TY_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef Trunk_W0r8S0Y3UGke6T9bIUWnnuw* TY_lh2A89ahMmYg9bCmpVaplLbA[256];
struct  Intset_EZObFrE3NC9bIb3YMkY9crZA  {
TY_lh2A89ahMmYg9bCmpVaplLbA data;
};
struct  Memregion_x81NhDv59b8ercDZ9bi85jyg  {
NI minlargeobj;
NI maxlargeobj;
TY_SiRwrEKZdLgxqz9a9aoVBglg freesmallchunks;
Llchunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk_Rv9c70Uhp2TytkX7eH78qEg* freechunkslist;
Intset_EZObFrE3NC9bIb3YMkY9crZA chunkstarts;
Avlnode_IaqjtwKhxLEpvDS9bct9blEw* root;
Avlnode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
Avlnode_IaqjtwKhxLEpvDS9bct9blEw* last;
Avlnode_IaqjtwKhxLEpvDS9bct9blEw* freeavlnodes;
NIM_BOOL locked;
NIM_BOOL blockchunksizeincrease;
NI nextchunksize;
};
struct  Gcstat_0RwLoVBHZPfUAcLczmfQAg  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Cellset_jG87P0AI9aZtss9ccTYBIISQ  {
NI counter;
NI max;
Pagedesc_fublkgIY4LG3mT51LU2WHg* head;
Pagedesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct  Gcheap_1TRH1TZMaVZTnLNcIHuNFQ  {
Gcstack_7fytPA5bBsob6See21YMRA* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq_Axo1XVm9aaQueTOldv8le5w zct;
Cellseq_Axo1XVm9aaQueTOldv8le5w decstack;
Cellseq_Axo1XVm9aaQueTOldv8le5w tempstack;
NI recgclock;
Memregion_x81NhDv59b8ercDZ9bi85jyg region;
Gcstat_0RwLoVBHZPfUAcLczmfQAg stat;
Cellset_jG87P0AI9aZtss9ccTYBIISQ marked;
Cellseq_Axo1XVm9aaQueTOldv8le5w additionalroots;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Gcstack_7fytPA5bBsob6See21YMRA  {
Gcstack_7fytPA5bBsob6See21YMRA* prev;
Gcstack_7fytPA5bBsob6See21YMRA* next;
void* starts;
void* pos;
NI maxstacksize;
};
struct  Basechunk_Sdq7WpT6qAH858F5ZEdG3w  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk_tXn60W2f8h3jgAYdEmy5NQ  {
  Basechunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
Smallchunk_tXn60W2f8h3jgAYdEmy5NQ* next;
Smallchunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
Freecell_u6M5LHprqzkn9axr04yg9bGQ* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk_XsENErzHIZV9bhvyJx56wGw  {
NI size;
NI acc;
Llchunk_XsENErzHIZV9bhvyJx56wGw* next;
};
struct  Bigchunk_Rv9c70Uhp2TytkX7eH78qEg  {
  Basechunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
Bigchunk_Rv9c70Uhp2TytkX7eH78qEg* next;
Bigchunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NI align;
NF data;
};
typedef NI TY_9a8QARi5WsUggNU9bom7kzTQ[8];
struct  Trunk_W0r8S0Y3UGke6T9bIUWnnuw  {
Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
TY_9a8QARi5WsUggNU9bom7kzTQ bits;
};
typedef Avlnode_IaqjtwKhxLEpvDS9bct9blEw* TY_0aOLqZchNi8nWtMTi8ND8w[2];
struct  Avlnode_IaqjtwKhxLEpvDS9bct9blEw  {
TY_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperbound;
NI level;
};
struct  Pagedesc_fublkgIY4LG3mT51LU2WHg  {
Pagedesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
TY_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct  Freecell_u6M5LHprqzkn9axr04yg9bGQ  {
Freecell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zerofield;
};
struct TY_bkMUR8maranmy38dEG39cHA {
  TGenericSeq Sup;
  TY_nEEz1gjcivYloysklmeNTg data[SEQ_DECL_SIZE];
};
struct TY_wQibBbBZLWmdoNxHgCZRyw {
  TGenericSeq Sup;
  TY_ponAwt7gy9asnIS681IafZQ data[SEQ_DECL_SIZE];
};
static N_INLINE(NI, hash_9c3uvkGO9cpD9a7QU6mLwadLAselectors)(int x0);
static N_INLINE(void, nimFrame)(TFrame* s0);
N_NOINLINE(void, stackoverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(void, HEX5BHEX5DHEX3D_3jMA6nwaCZ3e6Iyj5brtkg)(Table_bnna5wr180tUeaeDFxJ4xA* t0, int key0, Selectorkey_gE60aCfYXV1Nf1VTfPbepw val0);
static N_INLINE(NI, rawget_E9aV5vakSLJS0MAIqaecQsQtables)(Table_bnna5wr180tUeaeDFxJ4xA t0, int key0, NI* hc0);
static N_INLINE(NIM_BOOL, isfilled_IxXD1UAPoEehVDW9cv9cRaew_2tables)(NI hcode0);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, nexttry_OLPhxSyW9bte5CwHzzQVhfAtables)(NI h0, NI maxhash0);
static N_INLINE(NI, addInt)(NI a0, NI b0);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, subInt)(NI a0, NI b0);
N_NIMCALL(void, enlarge_XLab9bp69boKR7fPCKfFQ2hg)(Table_bnna5wr180tUeaeDFxJ4xA* t0);
N_NIMCALL(void, rawinsert_pD9czBD2OndL9cSDqb78Urig)(Table_bnna5wr180tUeaeDFxJ4xA* t0, TY_wQibBbBZLWmdoNxHgCZRyw** data0, int key0, Selectorkey_gE60aCfYXV1Nf1VTfPbepw val0, NI hc0, NI h0);
static N_INLINE(NI, rawgetknownhc_sVNCrVempRVYb0DwgWRB0Atables)(Table_bnna5wr180tUeaeDFxJ4xA t0, int key0, NI hc0);
N_NIMCALL(Selectorkey_gE60aCfYXV1Nf1VTfPbepw*, HEX5BHEX5D_Sd5XGNdJD9bEXX0z89aJkm7g)(Table_bnna5wr180tUeaeDFxJ4xA* t0, int key0);
N_NIMCALL(void, del_MPpoRTFhkQVAZDvswQqiSA)(Table_bnna5wr180tUeaeDFxJ4xA* t0, int key0);
N_NIMCALL(void, inittable_Hx3BnoioZlM0c7U4t1cT0w)(NI initialsize0, Table_bnna5wr180tUeaeDFxJ4xA* Result);
N_NIMCALL(NIM_BOOL, haskey_PW8rl8fmQKFFAo5bXDIQTQ)(Table_bnna5wr180tUeaeDFxJ4xA t0, int key0);
N_NIMCALL(void, HEX5BHEX5D_QeLiydbSBk8OZJj1o5uN0w)(Table_bnna5wr180tUeaeDFxJ4xA t0, int key0, Selectorkey_gE60aCfYXV1Nf1VTfPbepw* Result);
N_NIMCALL(void, register_QCHaUKprAzyUegaWtXEnGw)(Selector_X89cGFWVbzYzXTnuQzGngmA* s0, int fd0, Event_nI40bZzTyYVrl763dZ9aHDg_Set events0, TNimObject* data0);
static N_INLINE(NI, chckRange)(NI i0, NI a0, NI b0);
N_NOINLINE(void, raiseRangeError)(NI64 val0);
N_NOINLINE(void, raiseoserror_K9a7YBjj81Bse0N0Fg7MFIA)(NI32 errorcode0, NimStringDesc* additionalinfo0);
N_NIMCALL(NI32, oslasterror_pMOMIZAQaKFp1XoL58mjVg)(void);
N_NIMCALL(void, update_VzJ8OVqBzjqu4C23Nq9bPvg)(Selector_X89cGFWVbzYzXTnuQzGngmA* s0, int fd0, Event_nI40bZzTyYVrl763dZ9aHDg_Set events0);
N_NIMCALL(void, unregister_2fDHSfeVBEEsLBSaUEUOzA)(Selector_X89cGFWVbzYzXTnuQzGngmA* s0, int fd0);
N_NIMCALL(void, close_MwlkQPYetm2csv9bp6JpPWw)(Selector_X89cGFWVbzYzXTnuQzGngmA* s0);
N_NIMCALL(TY_bkMUR8maranmy38dEG39cHA*, select_HpncstI132GvQ9ceBTIOgrg)(Selector_X89cGFWVbzYzXTnuQzGngmA* s0, NI timeout0);
N_NIMCALL(void, nimGCvisit)(void* d0, NI op0);
static N_NIMCALL(void, Marker_TY_bkMUR8maranmy38dEG39cHA)(void* p, NI op);
N_NIMCALL(void*, newSeq)(TNimType* typ0, NI len0);
static N_INLINE(NI, divInt)(NI a0, NI b0);
N_NOINLINE(void, raiseDivByZero)(void);
N_NIMCALL(NI, mulInt)(NI a0, NI b0);
N_NIMCALL(void, failedassertimpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg0);
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq0, NI elemsize0);
static N_INLINE(void, asgnRef)(void** dest0, void* src0);
static N_INLINE(void, incref_9cAA5YuQAAC3MVbnGeV86swsystem)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c0);
static N_INLINE(Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrtocell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr0);
static N_INLINE(void, decref_MV4BBk6J1qu70IbBxwEn4wsystem)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c0);
static N_INLINE(void, rtladdzct_MV4BBk6J1qu70IbBxwEn4w_2system)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c0);
N_NOINLINE(void, addzct_fCDI7oO1NNVXXURtxSzsRw)(Cellseq_Axo1XVm9aaQueTOldv8le5w* s0, Cell_1zcF9cV8XIAtbN8h5HRUB8g* c0);
N_NIMCALL(void, newselector_tcCxAL6x4L39akwZ39aVA6Tg)(Selector_X89cGFWVbzYzXTnuQzGngmA* Result);
N_NIMCALL(NIM_BOOL, contains_uq4hmfvwPBm4HQD4ZQW6Kw)(Selector_X89cGFWVbzYzXTnuQzGngmA* s0, int fd0);
N_NIMCALL(void, HEX5BHEX5D_cRbUBRdnAVbKu6ptO8AZLQ)(Selector_X89cGFWVbzYzXTnuQzGngmA* s0, int fd0, Selectorkey_gE60aCfYXV1Nf1VTfPbepw* Result);
N_NOINLINE(void, chckNil)(void* p0);
N_NIMCALL(void, genericReset)(void* dest0, TNimType* mt0);
N_NIMCALL(NIM_BOOL, HEX3DHEX3D_fW6ECiKEQQ03nZ1qZlamvA)(Selectorkey_gE60aCfYXV1Nf1VTfPbepw x0, Selectorkey_gE60aCfYXV1Nf1VTfPbepw y0);
N_NIMCALL(NIM_BOOL, contains_qROqEyYt3sk1BLUMMnauEQ)(Selector_X89cGFWVbzYzXTnuQzGngmA* s0, Selectorkey_gE60aCfYXV1Nf1VTfPbepw key0);
N_NIMCALL(NI, len_Q1GsJskrVK5e0DS9cZT9bODg)(Table_bnna5wr180tUeaeDFxJ4xA t0);
N_NIMCALL(NI, len_6bMoxDMwI4Nef9a1VY5tbmw)(Selector_X89cGFWVbzYzXTnuQzGngmA* s0);
extern TFrame* frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw;
TNimType NTI_gE60aCfYXV1Nf1VTfPbepw;
extern TNimType NTI_nlCscttRCss70IBTyuBqnA;
TNimType NTI_nI40bZzTyYVrl763dZ9aHDg;
TNimType NTI_YIRsZrDT89buh37M5yeUgng;
extern TNimType NTI_1VeTzqrFu2VJ4a6cGvuoyA;
TNimType NTI_nEEz1gjcivYloysklmeNTg;
TNimType NTI_bkMUR8maranmy38dEG39cHA;
extern Gcheap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
TNimType NTI_X89cGFWVbzYzXTnuQzGngmA;
extern TNimType NTI_9cG9coEVt8bUEuxUupPPZigQ;
TNimType NTI_80NdCG41SyhPocFo20IbDw;
extern TNimType NTI_bnna5wr180tUeaeDFxJ4xA;
STRING_LITERAL(T_ln5vuDpFyDrAqQbYD2g52Q_9, "", 0);
STRING_LITERAL(T_ln5vuDpFyDrAqQbYD2g52Q_17, "\012  not (selectorKey.fd == SocketHandle(0)) ", 43);

static N_INLINE(void, nimFrame)(TFrame* s0) {
	NI LOC1;
	LOC1 = (NI)0;
	{
		if (!(frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s0).calldepth = ((NI16) (LOC1));
	(*s0).prev = frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw = s0;
	{
		if (!((*s0).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(NI, hash_9c3uvkGO9cpD9a7QU6mLwadLAselectors)(int x0) {
	NI result0;
	nimfr("hash", "hashes.nim")
	result0 = (NI)0;
	nimln(121, "hashes.nim");
	result0 = ((NI) (x0));
	popFrame();
	return result0;
}

static N_INLINE(NIM_BOOL, isfilled_IxXD1UAPoEehVDW9cv9cRaew_2tables)(NI hcode0) {
	NIM_BOOL result0;
	nimfr("isFilled", "tableimpl.nim")
	result0 = (NIM_BOOL)0;
	nimln(18, "tableimpl.nim");
	nimln(347, "system.nim");
	nimln(18, "tableimpl.nim");
	result0 = !((hcode0 == ((NI) 0)));
	popFrame();
	return result0;
}

static N_INLINE(NI, addInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU64)(a0) + (NU64)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ b0));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

static N_INLINE(NI, nexttry_OLPhxSyW9bte5CwHzzQVhfAtables)(NI h0, NI maxhash0) {
	NI result0;
	NI T_ln5vuDpFyDrAqQbYD2g52Q_6;
	nimfr("nextTry", "tableimpl.nim")
	result0 = (NI)0;
	nimln(28, "tableimpl.nim");
	T_ln5vuDpFyDrAqQbYD2g52Q_6 = addInt(h0, ((NI) 1));
	result0 = (NI)((NI)(T_ln5vuDpFyDrAqQbYD2g52Q_6) & maxhash0);
	popFrame();
	return result0;
}

static N_INLINE(NI, subInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU64)(a0) - (NU64)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ (NI)((NU64) ~(b0))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

static N_INLINE(NI, rawget_E9aV5vakSLJS0MAIqaecQsQtables)(Table_bnna5wr180tUeaeDFxJ4xA t0, int key0, NI* hc0) {
	NI result0;
	NI h0;
	NI T_ln5vuDpFyDrAqQbYD2g52Q_7;
	nimfr("rawGet", "tableimpl.nim")
{	result0 = (NI)0;
	nimln(43, "tableimpl.nim");
	(*hc0) = hash_9c3uvkGO9cpD9a7QU6mLwadLAselectors(key0);
	nimln(53, "tableimpl.nim");
	{
		if (!((*hc0) == ((NI) 0))) goto LA3;
		nimln(45, "tableimpl.nim");
		(*hc0) = ((NI) 314159265);
	}
	LA3: ;
	nimln(31, "tableimpl.nim");
	nimln(116, "tables.nim");
	h0 = (NI)((*hc0) & (t0.data ? (t0.data->Sup.len-1) : -1));
	{
		nimln(32, "tableimpl.nim");
		while (1) {
			NIM_BOOL LOC7;
			if ((NU)(h0) >= (NU)(t0.data->Sup.len)) raiseIndexError();
			LOC7 = (NIM_BOOL)0;
			LOC7 = isfilled_IxXD1UAPoEehVDW9cv9cRaew_2tables(t0.data->data[h0].Field0);
			if (!LOC7) goto LA6;
			nimln(37, "tableimpl.nim");
			{
				NIM_BOOL LOC10;
				LOC10 = (NIM_BOOL)0;
				if ((NU)(h0) >= (NU)(t0.data->Sup.len)) raiseIndexError();
				LOC10 = (t0.data->data[h0].Field0 == (*hc0));
				if (!(LOC10)) goto LA11;
				if ((NU)(h0) >= (NU)(t0.data->Sup.len)) raiseIndexError();
				LOC10 = (t0.data->data[h0].Field1 == key0);
				LA11: ;
				if (!LOC10) goto LA12;
				nimln(38, "tableimpl.nim");
				result0 = h0;
				goto BeforeRet;
			}
			LA12: ;
			nimln(39, "tableimpl.nim");
			nimln(116, "tables.nim");
			h0 = nexttry_OLPhxSyW9bte5CwHzzQVhfAtables(h0, (t0.data ? (t0.data->Sup.len-1) : -1));
		} LA6: ;
	}
	nimln(75, "tableimpl.nim");
	nimln(40, "tableimpl.nim");
	T_ln5vuDpFyDrAqQbYD2g52Q_7 = subInt(((NI) -1), h0);
	result0 = (NI)(T_ln5vuDpFyDrAqQbYD2g52Q_7);
	}BeforeRet: ;
	popFrame();
	return result0;
}

static N_INLINE(NI, rawgetknownhc_sVNCrVempRVYb0DwgWRB0Atables)(Table_bnna5wr180tUeaeDFxJ4xA t0, int key0, NI hc0) {
	NI result0;
	NI h0;
	NI T_ln5vuDpFyDrAqQbYD2g52Q_8;
	nimfr("rawGetKnownHC", "tableimpl.nim")
{	result0 = (NI)0;
	nimln(31, "tableimpl.nim");
	nimln(116, "tables.nim");
	h0 = (NI)(hc0 & (t0.data ? (t0.data->Sup.len-1) : -1));
	{
		nimln(32, "tableimpl.nim");
		while (1) {
			NIM_BOOL LOC3;
			if ((NU)(h0) >= (NU)(t0.data->Sup.len)) raiseIndexError();
			LOC3 = (NIM_BOOL)0;
			LOC3 = isfilled_IxXD1UAPoEehVDW9cv9cRaew_2tables(t0.data->data[h0].Field0);
			if (!LOC3) goto LA2;
			nimln(37, "tableimpl.nim");
			{
				NIM_BOOL LOC6;
				LOC6 = (NIM_BOOL)0;
				if ((NU)(h0) >= (NU)(t0.data->Sup.len)) raiseIndexError();
				LOC6 = (t0.data->data[h0].Field0 == hc0);
				if (!(LOC6)) goto LA7;
				if ((NU)(h0) >= (NU)(t0.data->Sup.len)) raiseIndexError();
				LOC6 = (t0.data->data[h0].Field1 == key0);
				LA7: ;
				if (!LOC6) goto LA8;
				nimln(38, "tableimpl.nim");
				result0 = h0;
				goto BeforeRet;
			}
			LA8: ;
			nimln(39, "tableimpl.nim");
			nimln(116, "tables.nim");
			h0 = nexttry_OLPhxSyW9bte5CwHzzQVhfAtables(h0, (t0.data ? (t0.data->Sup.len-1) : -1));
		} LA2: ;
	}
	nimln(69, "tableimpl.nim");
	nimln(40, "tableimpl.nim");
	T_ln5vuDpFyDrAqQbYD2g52Q_8 = subInt(((NI) -1), h0);
	result0 = (NI)(T_ln5vuDpFyDrAqQbYD2g52Q_8);
	}BeforeRet: ;
	popFrame();
	return result0;
}

static N_INLINE(NI, chckRange)(NI i0, NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (a0 <= i0);
		if (!(LOC3)) goto LA4;
		LOC3 = (i0 <= b0);
		LA4: ;
		if (!LOC3) goto LA5;
		result0 = i0;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i0)));
	}
	LA1: ;
	}BeforeRet: ;
	return result0;
}

N_NIMCALL(void, register_QCHaUKprAzyUegaWtXEnGw)(Selector_X89cGFWVbzYzXTnuQzGngmA* s0, int fd0, Event_nI40bZzTyYVrl763dZ9aHDg_Set events0, TNimObject* data0) {
	Selectorkey_gE60aCfYXV1Nf1VTfPbepw LOC21;
	nimfr("register", "selectors.nim")
	{
		Event_nI40bZzTyYVrl763dZ9aHDg event_mqVKst0L7ezoQyeQK9aRlYA;
		NI i_MPy4UPPdC9cgtPeLkX8p53w;
		event_mqVKst0L7ezoQyeQK9aRlYA = (Event_nI40bZzTyYVrl763dZ9aHDg)0;
		nimln(2033, "system.nim");
		i_MPy4UPPdC9cgtPeLkX8p53w = ((NI) 0);
		{
			nimln(2034, "system.nim");
			while (1) {
				NI T_ln5vuDpFyDrAqQbYD2g52Q_10;
				nimln(2033, "system.nim");
				if (!(i_MPy4UPPdC9cgtPeLkX8p53w <= ((NI) 2))) goto LA3;
				nimln(2035, "system.nim");
				{
					struct kevent kev_hnKZNf9bNeqgRSEP7S5eKZg;
					struct kevent LOC8;
					NI LOC9;
					nimln(222, "selectors.nim");
					if (!((events0 &(1U<<((NU)(((Event_nI40bZzTyYVrl763dZ9aHDg)chckRange(i_MPy4UPPdC9cgtPeLkX8p53w, ((Event_nI40bZzTyYVrl763dZ9aHDg) 0), ((Event_nI40bZzTyYVrl763dZ9aHDg) 2))))&7U)))!=0)) goto LA6;
					nimln(2035, "system.nim");
					event_mqVKst0L7ezoQyeQK9aRlYA = ((Event_nI40bZzTyYVrl763dZ9aHDg)chckRange(i_MPy4UPPdC9cgtPeLkX8p53w, ((Event_nI40bZzTyYVrl763dZ9aHDg) 0), ((Event_nI40bZzTyYVrl763dZ9aHDg) 2)));
					nimln(214, "selectors.nim");
					memset((void*)(&LOC8), 0, sizeof(LOC8));
					LOC8.ident = ((NU) (((unsigned int) (fd0))));
					LOC9 = (NI)0;
					nimln(215, "selectors.nim");
					{
						nimln(223, "selectors.nim");
						if (!(event_mqVKst0L7ezoQyeQK9aRlYA == ((Event_nI40bZzTyYVrl763dZ9aHDg) 0))) goto LA12;
						LOC9 = ((NI) -1);
					}
					goto LA10;
					LA12: ;
					{
						LOC9 = ((NI) -2);
					}
					LA10: ;
					LOC8.filter = ((short)chckRange(LOC9, ((short) -32768), ((short) 32767)));
					LOC8.flags = ((unsigned short) 1);
					kev_hnKZNf9bNeqgRSEP7S5eKZg = LOC8;
					{
						int LOC17;
						NI32 LOC20;
						nimln(217, "selectors.nim");
						nimln(223, "selectors.nim");
						LOC17 = (int)0;
						LOC17 = kevent((*s0).kqfd, (&kev_hnKZNf9bNeqgRSEP7S5eKZg), ((int) 1), NIM_NIL, ((int) 0), NIM_NIL);
						if (!(LOC17 == ((NI32) -1))) goto LA18;
						nimln(218, "selectors.nim");
						LOC20 = (NI32)0;
						LOC20 = oslasterror_pMOMIZAQaKFp1XoL58mjVg();
						raiseoserror_K9a7YBjj81Bse0N0Fg7MFIA(LOC20, ((NimStringDesc*) &T_ln5vuDpFyDrAqQbYD2g52Q_9));
					}
					LA18: ;
				}
				LA6: ;
				nimln(2033, "system.nim");
				T_ln5vuDpFyDrAqQbYD2g52Q_10 = addInt(i_MPy4UPPdC9cgtPeLkX8p53w, ((NI) 1));
				i_MPy4UPPdC9cgtPeLkX8p53w = (NI)(T_ln5vuDpFyDrAqQbYD2g52Q_10);
			} LA3: ;
		}
	}
	nimln(224, "selectors.nim");
	memset((void*)(&LOC21), 0, sizeof(LOC21));
	memset((void*)(&LOC21), 0, sizeof(LOC21));
	LOC21.fd = fd0;
	LOC21.events = events0;
	LOC21.data = data0;
	HEX5BHEX5DHEX3D_3jMA6nwaCZ3e6Iyj5brtkg((&(*s0).fds), fd0, LOC21);
	popFrame();
}

N_NIMCALL(void, update_VzJ8OVqBzjqu4C23Nq9bPvg)(Selector_X89cGFWVbzYzXTnuQzGngmA* s0, int fd0, Event_nI40bZzTyYVrl763dZ9aHDg_Set events0) {
	Event_nI40bZzTyYVrl763dZ9aHDg_Set previousevents0;
	Selectorkey_gE60aCfYXV1Nf1VTfPbepw* LOC1;
	nimfr("update", "selectors.nim")
	nimln(227, "selectors.nim");
	LOC1 = (Selectorkey_gE60aCfYXV1Nf1VTfPbepw*)0;
	LOC1 = HEX5BHEX5D_Sd5XGNdJD9bEXX0z89aJkm7g((&(*s0).fds), fd0);
	previousevents0 = (*LOC1).events;
	nimln(228, "selectors.nim");
	{
		Selectorkey_gE60aCfYXV1Nf1VTfPbepw* LOC46;
		nimln(347, "system.nim");
		nimln(228, "selectors.nim");
		if (!!((previousevents0 == events0))) goto LA4;
		{
			Event_nI40bZzTyYVrl763dZ9aHDg event_meBNHX4HjhL3Xu2RhqAIFQ;
			Event_nI40bZzTyYVrl763dZ9aHDg_Set HEX3Atmp_nxCAoark5Ze9bhyPEtWZQQA;
			NI i_XxfdrdHx9arH1IZ9cvxSSyPA;
			event_meBNHX4HjhL3Xu2RhqAIFQ = (Event_nI40bZzTyYVrl763dZ9aHDg)0;
			memset((void*)(&HEX3Atmp_nxCAoark5Ze9bhyPEtWZQQA), 0, sizeof(HEX3Atmp_nxCAoark5Ze9bhyPEtWZQQA));
			nimln(229, "selectors.nim");
			HEX3Atmp_nxCAoark5Ze9bhyPEtWZQQA = (events0 & ~ previousevents0);
			nimln(2033, "system.nim");
			i_XxfdrdHx9arH1IZ9cvxSSyPA = ((NI) 0);
			{
				nimln(2034, "system.nim");
				while (1) {
					NI T_ln5vuDpFyDrAqQbYD2g52Q_11;
					nimln(2033, "system.nim");
					if (!(i_XxfdrdHx9arH1IZ9cvxSSyPA <= ((NI) 2))) goto LA8;
					nimln(2035, "system.nim");
					{
						struct kevent kev_hOjI9bcRjJJYat7iQSWyaJw;
						struct kevent LOC13;
						NI LOC14;
						nimln(2029, "system.nim");
						if (!((HEX3Atmp_nxCAoark5Ze9bhyPEtWZQQA &(1U<<((NU)(((Event_nI40bZzTyYVrl763dZ9aHDg)chckRange(i_XxfdrdHx9arH1IZ9cvxSSyPA, ((Event_nI40bZzTyYVrl763dZ9aHDg) 0), ((Event_nI40bZzTyYVrl763dZ9aHDg) 2))))&7U)))!=0)) goto LA11;
						nimln(2035, "system.nim");
						event_meBNHX4HjhL3Xu2RhqAIFQ = ((Event_nI40bZzTyYVrl763dZ9aHDg)chckRange(i_XxfdrdHx9arH1IZ9cvxSSyPA, ((Event_nI40bZzTyYVrl763dZ9aHDg) 0), ((Event_nI40bZzTyYVrl763dZ9aHDg) 2)));
						nimln(214, "selectors.nim");
						memset((void*)(&LOC13), 0, sizeof(LOC13));
						LOC13.ident = ((NU) (((unsigned int) (fd0))));
						LOC14 = (NI)0;
						nimln(215, "selectors.nim");
						{
							nimln(230, "selectors.nim");
							if (!(event_meBNHX4HjhL3Xu2RhqAIFQ == ((Event_nI40bZzTyYVrl763dZ9aHDg) 0))) goto LA17;
							LOC14 = ((NI) -1);
						}
						goto LA15;
						LA17: ;
						{
							LOC14 = ((NI) -2);
						}
						LA15: ;
						LOC13.filter = ((short)chckRange(LOC14, ((short) -32768), ((short) 32767)));
						LOC13.flags = ((unsigned short) 1);
						kev_hOjI9bcRjJJYat7iQSWyaJw = LOC13;
						{
							int LOC22;
							NI32 LOC25;
							nimln(217, "selectors.nim");
							nimln(230, "selectors.nim");
							LOC22 = (int)0;
							LOC22 = kevent((*s0).kqfd, (&kev_hOjI9bcRjJJYat7iQSWyaJw), ((int) 1), NIM_NIL, ((int) 0), NIM_NIL);
							if (!(LOC22 == ((NI32) -1))) goto LA23;
							nimln(218, "selectors.nim");
							LOC25 = (NI32)0;
							LOC25 = oslasterror_pMOMIZAQaKFp1XoL58mjVg();
							raiseoserror_K9a7YBjj81Bse0N0Fg7MFIA(LOC25, ((NimStringDesc*) &T_ln5vuDpFyDrAqQbYD2g52Q_9));
						}
						LA23: ;
					}
					LA11: ;
					nimln(2033, "system.nim");
					T_ln5vuDpFyDrAqQbYD2g52Q_11 = addInt(i_XxfdrdHx9arH1IZ9cvxSSyPA, ((NI) 1));
					i_XxfdrdHx9arH1IZ9cvxSSyPA = (NI)(T_ln5vuDpFyDrAqQbYD2g52Q_11);
				} LA8: ;
			}
		}
		{
			Event_nI40bZzTyYVrl763dZ9aHDg event_meBNHX4HjhL3Xu2RhqAIFQ_2;
			Event_nI40bZzTyYVrl763dZ9aHDg_Set HEX3Atmp_nxCAoark5Ze9bhyPEtWZQQA_2;
			NI i_XxfdrdHx9arH1IZ9cvxSSyPA_2;
			event_meBNHX4HjhL3Xu2RhqAIFQ_2 = (Event_nI40bZzTyYVrl763dZ9aHDg)0;
			memset((void*)(&HEX3Atmp_nxCAoark5Ze9bhyPEtWZQQA_2), 0, sizeof(HEX3Atmp_nxCAoark5Ze9bhyPEtWZQQA_2));
			nimln(231, "selectors.nim");
			HEX3Atmp_nxCAoark5Ze9bhyPEtWZQQA_2 = (previousevents0 & ~ events0);
			nimln(2033, "system.nim");
			i_XxfdrdHx9arH1IZ9cvxSSyPA_2 = ((NI) 0);
			{
				nimln(2034, "system.nim");
				while (1) {
					NI T_ln5vuDpFyDrAqQbYD2g52Q_12;
					nimln(2033, "system.nim");
					if (!(i_XxfdrdHx9arH1IZ9cvxSSyPA_2 <= ((NI) 2))) goto LA28;
					nimln(2035, "system.nim");
					{
						struct kevent kev_hOjI9bcRjJJYat7iQSWyaJw_2;
						struct kevent LOC33;
						NI LOC34;
						nimln(2029, "system.nim");
						if (!((HEX3Atmp_nxCAoark5Ze9bhyPEtWZQQA_2 &(1U<<((NU)(((Event_nI40bZzTyYVrl763dZ9aHDg)chckRange(i_XxfdrdHx9arH1IZ9cvxSSyPA_2, ((Event_nI40bZzTyYVrl763dZ9aHDg) 0), ((Event_nI40bZzTyYVrl763dZ9aHDg) 2))))&7U)))!=0)) goto LA31;
						nimln(2035, "system.nim");
						event_meBNHX4HjhL3Xu2RhqAIFQ_2 = ((Event_nI40bZzTyYVrl763dZ9aHDg)chckRange(i_XxfdrdHx9arH1IZ9cvxSSyPA_2, ((Event_nI40bZzTyYVrl763dZ9aHDg) 0), ((Event_nI40bZzTyYVrl763dZ9aHDg) 2)));
						nimln(214, "selectors.nim");
						memset((void*)(&LOC33), 0, sizeof(LOC33));
						LOC33.ident = ((NU) (((unsigned int) (fd0))));
						LOC34 = (NI)0;
						nimln(215, "selectors.nim");
						{
							nimln(232, "selectors.nim");
							if (!(event_meBNHX4HjhL3Xu2RhqAIFQ_2 == ((Event_nI40bZzTyYVrl763dZ9aHDg) 0))) goto LA37;
							LOC34 = ((NI) -1);
						}
						goto LA35;
						LA37: ;
						{
							LOC34 = ((NI) -2);
						}
						LA35: ;
						LOC33.filter = ((short)chckRange(LOC34, ((short) -32768), ((short) 32767)));
						LOC33.flags = ((unsigned short) 2);
						kev_hOjI9bcRjJJYat7iQSWyaJw_2 = LOC33;
						{
							int LOC42;
							NI32 LOC45;
							nimln(217, "selectors.nim");
							nimln(232, "selectors.nim");
							LOC42 = (int)0;
							LOC42 = kevent((*s0).kqfd, (&kev_hOjI9bcRjJJYat7iQSWyaJw_2), ((int) 1), NIM_NIL, ((int) 0), NIM_NIL);
							if (!(LOC42 == ((NI32) -1))) goto LA43;
							nimln(218, "selectors.nim");
							LOC45 = (NI32)0;
							LOC45 = oslasterror_pMOMIZAQaKFp1XoL58mjVg();
							raiseoserror_K9a7YBjj81Bse0N0Fg7MFIA(LOC45, ((NimStringDesc*) &T_ln5vuDpFyDrAqQbYD2g52Q_9));
						}
						LA43: ;
					}
					LA31: ;
					nimln(2033, "system.nim");
					T_ln5vuDpFyDrAqQbYD2g52Q_12 = addInt(i_XxfdrdHx9arH1IZ9cvxSSyPA_2, ((NI) 1));
					i_XxfdrdHx9arH1IZ9cvxSSyPA_2 = (NI)(T_ln5vuDpFyDrAqQbYD2g52Q_12);
				} LA28: ;
			}
		}
		nimln(233, "selectors.nim");
		LOC46 = (Selectorkey_gE60aCfYXV1Nf1VTfPbepw*)0;
		LOC46 = HEX5BHEX5D_Sd5XGNdJD9bEXX0z89aJkm7g((&(*s0).fds), fd0);
		(*LOC46).events = events0;
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(void, unregister_2fDHSfeVBEEsLBSaUEUOzA)(Selector_X89cGFWVbzYzXTnuQzGngmA* s0, int fd0) {
	nimfr("unregister", "selectors.nim")
	{
		Event_nI40bZzTyYVrl763dZ9aHDg event_P8iTuOTVj9bqzs7pF8ZNH4w;
		Event_nI40bZzTyYVrl763dZ9aHDg_Set HEX3Atmp_M62meMTAus1tldPImmttVQ;
		Selectorkey_gE60aCfYXV1Nf1VTfPbepw* LOC2;
		NI i_4f9bi9budeiTwVBPbI1Q3oJA;
		event_P8iTuOTVj9bqzs7pF8ZNH4w = (Event_nI40bZzTyYVrl763dZ9aHDg)0;
		memset((void*)(&HEX3Atmp_M62meMTAus1tldPImmttVQ), 0, sizeof(HEX3Atmp_M62meMTAus1tldPImmttVQ));
		nimln(236, "selectors.nim");
		LOC2 = (Selectorkey_gE60aCfYXV1Nf1VTfPbepw*)0;
		LOC2 = HEX5BHEX5D_Sd5XGNdJD9bEXX0z89aJkm7g((&(*s0).fds), fd0);
		HEX3Atmp_M62meMTAus1tldPImmttVQ = (*LOC2).events;
		nimln(2033, "system.nim");
		i_4f9bi9budeiTwVBPbI1Q3oJA = ((NI) 0);
		{
			nimln(2034, "system.nim");
			while (1) {
				NI T_ln5vuDpFyDrAqQbYD2g52Q_13;
				nimln(2033, "system.nim");
				if (!(i_4f9bi9budeiTwVBPbI1Q3oJA <= ((NI) 2))) goto LA4;
				nimln(2035, "system.nim");
				{
					struct kevent kev_VtNK9cEOLelrN6gFifOEudQ;
					struct kevent LOC9;
					NI LOC10;
					nimln(2029, "system.nim");
					if (!((HEX3Atmp_M62meMTAus1tldPImmttVQ &(1U<<((NU)(((Event_nI40bZzTyYVrl763dZ9aHDg)chckRange(i_4f9bi9budeiTwVBPbI1Q3oJA, ((Event_nI40bZzTyYVrl763dZ9aHDg) 0), ((Event_nI40bZzTyYVrl763dZ9aHDg) 2))))&7U)))!=0)) goto LA7;
					nimln(2035, "system.nim");
					event_P8iTuOTVj9bqzs7pF8ZNH4w = ((Event_nI40bZzTyYVrl763dZ9aHDg)chckRange(i_4f9bi9budeiTwVBPbI1Q3oJA, ((Event_nI40bZzTyYVrl763dZ9aHDg) 0), ((Event_nI40bZzTyYVrl763dZ9aHDg) 2)));
					nimln(214, "selectors.nim");
					memset((void*)(&LOC9), 0, sizeof(LOC9));
					LOC9.ident = ((NU) (((unsigned int) (fd0))));
					LOC10 = (NI)0;
					nimln(215, "selectors.nim");
					{
						nimln(237, "selectors.nim");
						if (!(event_P8iTuOTVj9bqzs7pF8ZNH4w == ((Event_nI40bZzTyYVrl763dZ9aHDg) 0))) goto LA13;
						LOC10 = ((NI) -1);
					}
					goto LA11;
					LA13: ;
					{
						LOC10 = ((NI) -2);
					}
					LA11: ;
					LOC9.filter = ((short)chckRange(LOC10, ((short) -32768), ((short) 32767)));
					LOC9.flags = ((unsigned short) 2);
					kev_VtNK9cEOLelrN6gFifOEudQ = LOC9;
					{
						int LOC18;
						NI32 LOC21;
						nimln(217, "selectors.nim");
						nimln(237, "selectors.nim");
						LOC18 = (int)0;
						LOC18 = kevent((*s0).kqfd, (&kev_VtNK9cEOLelrN6gFifOEudQ), ((int) 1), NIM_NIL, ((int) 0), NIM_NIL);
						if (!(LOC18 == ((NI32) -1))) goto LA19;
						nimln(218, "selectors.nim");
						LOC21 = (NI32)0;
						LOC21 = oslasterror_pMOMIZAQaKFp1XoL58mjVg();
						raiseoserror_K9a7YBjj81Bse0N0Fg7MFIA(LOC21, ((NimStringDesc*) &T_ln5vuDpFyDrAqQbYD2g52Q_9));
					}
					LA19: ;
				}
				LA7: ;
				nimln(2033, "system.nim");
				T_ln5vuDpFyDrAqQbYD2g52Q_13 = addInt(i_4f9bi9budeiTwVBPbI1Q3oJA, ((NI) 1));
				i_4f9bi9budeiTwVBPbI1Q3oJA = (NI)(T_ln5vuDpFyDrAqQbYD2g52Q_13);
			} LA4: ;
		}
	}
	nimln(238, "selectors.nim");
	del_MPpoRTFhkQVAZDvswQqiSA((&(*s0).fds), fd0);
	popFrame();
}

N_NIMCALL(void, close_MwlkQPYetm2csv9bp6JpPWw)(Selector_X89cGFWVbzYzXTnuQzGngmA* s0) {
	nimfr("close", "selectors.nim")
	nimln(242, "selectors.nim");
	{
		int LOC3;
		NI32 LOC6;
		nimln(347, "system.nim");
		nimln(242, "selectors.nim");
		LOC3 = (int)0;
		LOC3 = close((*s0).kqfd);
		if (!!((LOC3 == ((NI32) 0)))) goto LA4;
		LOC6 = (NI32)0;
		LOC6 = oslasterror_pMOMIZAQaKFp1XoL58mjVg();
		raiseoserror_K9a7YBjj81Bse0N0Fg7MFIA(LOC6, ((NimStringDesc*) &T_ln5vuDpFyDrAqQbYD2g52Q_9));
	}
	LA4: ;
	popFrame();
}
static N_NIMCALL(void, Marker_TY_bkMUR8maranmy38dEG39cHA)(void* p, NI op) {
	TY_bkMUR8maranmy38dEG39cHA* a;
	NI LOC1;
	a = (TY_bkMUR8maranmy38dEG39cHA*)p;
	LOC1 = (NI)0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1].Field0.data, op);
	}
}

static N_INLINE(NI, divInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	{
		if (!(b0 == ((NI) 0))) goto LA3;
		raiseDivByZero();
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = (NIM_BOOL)0;
		LOC7 = (a0 == ((NI) (IL64(-9223372036854775807) - IL64(1))));
		if (!(LOC7)) goto LA8;
		LOC7 = (b0 == ((NI) -1));
		LA8: ;
		if (!LOC7) goto LA9;
		raiseOverflow();
	}
	LA9: ;
	result0 = (NI)(a0 / b0);
	goto BeforeRet;
	}BeforeRet: ;
	return result0;
}

static N_INLINE(void, incref_9cAA5YuQAAC3MVbnGeV86swsystem)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c0) {
	nimfr("incRef", "gc.nim")
	nimln(232, "gc.nim");
	(*c0).refcount = (NI)((NU64)((*c0).refcount) + (NU64)(((NI) 8)));
	popFrame();
}

static N_INLINE(Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrtocell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr0) {
	Cell_1zcF9cV8XIAtbN8h5HRUB8g* result0;
	nimfr("usrToCell", "gc.nim")
	result0 = (Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln(134, "gc.nim");
	result0 = ((Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (usr0))) - (NU64)(((NI)sizeof(Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result0;
}

static N_INLINE(void, rtladdzct_MV4BBk6J1qu70IbBxwEn4w_2system)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c0) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(220, "gc.nim");
	addzct_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c0);
	popFrame();
}

static N_INLINE(void, decref_MV4BBk6J1qu70IbBxwEn4wsystem)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c0) {
	nimfr("decRef", "gc.nim")
	nimln(227, "gc.nim");
	{
		(*c0).refcount -= ((NI) 8);
		if (!((NU64)((*c0).refcount) < (NU64)(((NI) 8)))) goto LA3;
		nimln(228, "gc.nim");
		rtladdzct_MV4BBk6J1qu70IbBxwEn4w_2system(c0);
	}
	LA3: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest0, void* src0) {
	nimfr("asgnRef", "gc.nim")
	nimln(273, "gc.nim");
	{
		Cell_1zcF9cV8XIAtbN8h5HRUB8g* LOC5;
		nimln(347, "system.nim");
		nimln(273, "gc.nim");
		if (!!((src0 == NIM_NIL))) goto LA3;
		LOC5 = (Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		LOC5 = usrtocell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src0);
		incref_9cAA5YuQAAC3MVbnGeV86swsystem(LOC5);
	}
	LA3: ;
	nimln(274, "gc.nim");
	{
		Cell_1zcF9cV8XIAtbN8h5HRUB8g* LOC10;
		nimln(347, "system.nim");
		nimln(274, "gc.nim");
		if (!!(((*dest0) == NIM_NIL))) goto LA8;
		LOC10 = (Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		LOC10 = usrtocell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest0));
		decref_MV4BBk6J1qu70IbBxwEn4wsystem(LOC10);
	}
	LA8: ;
	nimln(275, "gc.nim");
	(*dest0) = src0;
	popFrame();
}

N_NIMCALL(TY_bkMUR8maranmy38dEG39cHA*, select_HpncstI132GvQ9ceBTIOgrg)(Selector_X89cGFWVbzYzXTnuQzGngmA* s0, NI timeout0) {
	TY_bkMUR8maranmy38dEG39cHA* result0;
	struct timespec tv0;
	int evnum0;
	nimfr("select", "selectors.nim")
{	result0 = (TY_bkMUR8maranmy38dEG39cHA*)0;
	nimln(245, "selectors.nim");
	result0 = (TY_bkMUR8maranmy38dEG39cHA*) newSeq((&NTI_bkMUR8maranmy38dEG39cHA), 0);
	nimln(246, "selectors.nim");
	nimln(247, "selectors.nim");
	{
		struct timespec LOC5;
		NI T_ln5vuDpFyDrAqQbYD2g52Q_15;
		if (!(((NI) 1000) <= timeout0)) goto LA3;
		memset((void*)(&LOC5), 0, sizeof(LOC5));
		T_ln5vuDpFyDrAqQbYD2g52Q_15 = divInt(timeout0, ((NI) 1000));
		LOC5.tv_sec = (NI)(T_ln5vuDpFyDrAqQbYD2g52Q_15);
		LOC5.tv_nsec = ((NI) 0);
		tv0 = LOC5;
	}
	goto LA1;
	LA3: ;
	{
		struct timespec LOC7;
		NI T_ln5vuDpFyDrAqQbYD2g52Q_16;
		memset((void*)(&LOC7), 0, sizeof(LOC7));
		LOC7.tv_sec = ((time_t) 0);
		nimln(248, "selectors.nim");
		T_ln5vuDpFyDrAqQbYD2g52Q_16 = mulInt(timeout0, ((NI) 1000000));
		LOC7.tv_nsec = (NI)(T_ln5vuDpFyDrAqQbYD2g52Q_16);
		tv0 = LOC7;
	}
	LA1: ;
	nimln(249, "selectors.nim");
	evnum0 = kevent((*s0).kqfd, NIM_NIL, ((int) 0), (&(*s0).events[(((NI) 0))- 0]), ((int) 64), (&tv0));
	nimln(250, "selectors.nim");
	{
		NI32 err0;
		if (!(evnum0 < ((NI32) 0))) goto LA10;
		nimln(251, "selectors.nim");
		err0 = oslasterror_pMOMIZAQaKFp1XoL58mjVg();
		nimln(252, "selectors.nim");
		{
			if (!(err0 == EINTR)) goto LA14;
			nimln(253, "selectors.nim");
			result0 = (TY_bkMUR8maranmy38dEG39cHA*) newSeq((&NTI_bkMUR8maranmy38dEG39cHA), 0);
			goto BeforeRet;
		}
		LA14: ;
		nimln(254, "selectors.nim");
		raiseoserror_K9a7YBjj81Bse0N0Fg7MFIA(err0, ((NimStringDesc*) &T_ln5vuDpFyDrAqQbYD2g52Q_9));
	}
	LA10: ;
	nimln(255, "selectors.nim");
	{
		if (!(evnum0 == ((NI32) 0))) goto LA18;
		result0 = (TY_bkMUR8maranmy38dEG39cHA*) newSeq((&NTI_bkMUR8maranmy38dEG39cHA), 0);
		goto BeforeRet;
	}
	LA18: ;
	{
		int i_G2aNgotvyNgCmEeJt7MaUg;
		int HEX3Atmp_VZtRxmNtWeoJoc6mALBNPw;
		NI res_4x6E9aozdZBDkmdCLxZt9bjQ;
		i_G2aNgotvyNgCmEeJt7MaUg = (int)0;
		HEX3Atmp_VZtRxmNtWeoJoc6mALBNPw = (int)0;
		nimln(256, "selectors.nim");
		HEX3Atmp_VZtRxmNtWeoJoc6mALBNPw = subInt(evnum0, 1);
		nimln(1908, "system.nim");
		res_4x6E9aozdZBDkmdCLxZt9bjQ = ((NI) 0);
		{
			nimln(1909, "system.nim");
			while (1) {
				int fd0;
				Event_nI40bZzTyYVrl763dZ9aHDg_Set evset0;
				Selectorkey_gE60aCfYXV1Nf1VTfPbepw selectorkey0;
				Selectorkey_gE60aCfYXV1Nf1VTfPbepw* LOC34;
				TY_nEEz1gjcivYloysklmeNTg LOC39;
				NI T_ln5vuDpFyDrAqQbYD2g52Q_18;
				nimln(1908, "system.nim");
				if (!(res_4x6E9aozdZBDkmdCLxZt9bjQ <= ((NI) (HEX3Atmp_VZtRxmNtWeoJoc6mALBNPw)))) goto LA22;
				nimln(1910, "system.nim");
				i_G2aNgotvyNgCmEeJt7MaUg = ((int)chckRange(res_4x6E9aozdZBDkmdCLxZt9bjQ, ((int) (-2147483647 -1)), ((int) 2147483647)));
				nimln(257, "selectors.nim");
				if ((NU)(i_G2aNgotvyNgCmEeJt7MaUg) > (NU)(63)) raiseIndexError();
				fd0 = ((int) ((*s0).events[(i_G2aNgotvyNgCmEeJt7MaUg)- 0].ident));
				nimln(259, "selectors.nim");
				evset0 = 0;
				nimln(260, "selectors.nim");
				{
					nimln(347, "system.nim");
					nimln(260, "selectors.nim");
					if ((NU)(i_G2aNgotvyNgCmEeJt7MaUg) > (NU)(63)) raiseIndexError();
					if (!!(((NU16)((*s0).events[(i_G2aNgotvyNgCmEeJt7MaUg)- 0].flags & ((NI) 32768)) == ((NI) 0)))) goto LA25;
					evset0 = (evset0 | 4);
				}
				LA25: ;
				nimln(261, "selectors.nim");
				{
					if ((NU)(i_G2aNgotvyNgCmEeJt7MaUg) > (NU)(63)) raiseIndexError();
					if (!((*s0).events[(i_G2aNgotvyNgCmEeJt7MaUg)- 0].filter == ((NI16) -1))) goto LA29;
					evset0 = (evset0 | 1);
				}
				goto LA27;
				LA29: ;
				{
					nimln(262, "selectors.nim");
					if ((NU)(i_G2aNgotvyNgCmEeJt7MaUg) > (NU)(63)) raiseIndexError();
					if (!((*s0).events[(i_G2aNgotvyNgCmEeJt7MaUg)- 0].filter == ((NI16) -2))) goto LA32;
					evset0 = (evset0 | 2);
				}
				goto LA27;
				LA32: ;
				LA27: ;
				memset((void*)(&selectorkey0), 0, sizeof(selectorkey0));
				nimln(263, "selectors.nim");
				LOC34 = (Selectorkey_gE60aCfYXV1Nf1VTfPbepw*)0;
				LOC34 = HEX5BHEX5D_Sd5XGNdJD9bEXX0z89aJkm7g((&(*s0).fds), fd0);
				selectorkey0.fd = (*LOC34).fd;
				selectorkey0.events = (*LOC34).events;
				selectorkey0.data = (*LOC34).data;
				nimln(264, "selectors.nim");
				{
					if (!!(!((selectorkey0.fd == ((int) 0))))) goto LA37;
					failedassertimpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &T_ln5vuDpFyDrAqQbYD2g52Q_17));
				}
				LA37: ;
				nimln(265, "selectors.nim");
				memset((void*)(&LOC39), 0, sizeof(LOC39));
				LOC39.Field0.fd = selectorkey0.fd;
				LOC39.Field0.events = selectorkey0.events;
				LOC39.Field0.data = selectorkey0.data;
				LOC39.Field1 = evset0;
				result0 = (TY_bkMUR8maranmy38dEG39cHA*) incrSeqV2(&(result0)->Sup, sizeof(TY_nEEz1gjcivYloysklmeNTg));
				result0->data[result0->Sup.len].Field0.fd = LOC39.Field0.fd;
				result0->data[result0->Sup.len].Field0.events = LOC39.Field0.events;
				asgnRef((void**) (&result0->data[result0->Sup.len].Field0.data), LOC39.Field0.data);
				result0->data[result0->Sup.len].Field1 = LOC39.Field1;
				++result0->Sup.len;
				nimln(1908, "system.nim");
				T_ln5vuDpFyDrAqQbYD2g52Q_18 = addInt(res_4x6E9aozdZBDkmdCLxZt9bjQ, ((NI) 1));
				res_4x6E9aozdZBDkmdCLxZt9bjQ = (NI)(T_ln5vuDpFyDrAqQbYD2g52Q_18);
			} LA22: ;
		}
	}
	}BeforeRet: ;
	popFrame();
	return result0;
}

N_NIMCALL(void, newselector_tcCxAL6x4L39akwZ39aVA6Tg)(Selector_X89cGFWVbzYzXTnuQzGngmA* Result) {
	nimfr("newSelector", "selectors.nim")
	nimln(268, "selectors.nim");
	(*Result).kqfd = kqueue();
	nimln(269, "selectors.nim");
	{
		NI32 LOC5;
		if (!((*Result).kqfd < ((NI32) 0))) goto LA3;
		nimln(270, "selectors.nim");
		LOC5 = (NI32)0;
		LOC5 = oslasterror_pMOMIZAQaKFp1XoL58mjVg();
		raiseoserror_K9a7YBjj81Bse0N0Fg7MFIA(LOC5, ((NimStringDesc*) &T_ln5vuDpFyDrAqQbYD2g52Q_9));
	}
	LA3: ;
	nimln(274, "selectors.nim");
	inittable_Hx3BnoioZlM0c7U4t1cT0w(((NI) 64), (&(*Result).fds));
	popFrame();
}

N_NIMCALL(NIM_BOOL, contains_uq4hmfvwPBm4HQD4ZQW6Kw)(Selector_X89cGFWVbzYzXTnuQzGngmA* s0, int fd0) {
	NIM_BOOL result0;
	nimfr("contains", "selectors.nim")
	result0 = (NIM_BOOL)0;
	nimln(277, "selectors.nim");
	nimln(278, "selectors.nim");
	result0 = haskey_PW8rl8fmQKFFAo5bXDIQTQ((*s0).fds, fd0);
	popFrame();
	return result0;
}

N_NIMCALL(void, HEX5BHEX5D_cRbUBRdnAVbKu6ptO8AZLQ)(Selector_X89cGFWVbzYzXTnuQzGngmA* s0, int fd0, Selectorkey_gE60aCfYXV1Nf1VTfPbepw* Result) {
	nimfr("[]", "selectors.nim")
{	nimln(282, "selectors.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_gE60aCfYXV1Nf1VTfPbepw));
	HEX5BHEX5D_QeLiydbSBk8OZJj1o5uN0w((*s0).fds, fd0, Result);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
}

N_NIMCALL(NIM_BOOL, contains_qROqEyYt3sk1BLUMMnauEQ)(Selector_X89cGFWVbzYzXTnuQzGngmA* s0, Selectorkey_gE60aCfYXV1Nf1VTfPbepw key0) {
	NIM_BOOL result0;
	NIM_BOOL LOC1;
	Selectorkey_gE60aCfYXV1Nf1VTfPbepw LOC3;
	nimfr("contains", "selectors.nim")
{	result0 = (NIM_BOOL)0;
	nimln(376, "selectors.nim");
	LOC1 = (NIM_BOOL)0;
	LOC1 = contains_uq4hmfvwPBm4HQD4ZQW6Kw(s0, key0.fd);
	if (!(LOC1)) goto LA2;
	memset((void*)(&LOC3), 0, sizeof(LOC3));
	HEX5BHEX5D_QeLiydbSBk8OZJj1o5uN0w((*s0).fds, key0.fd, (&LOC3));
	LOC1 = HEX3DHEX3D_fW6ECiKEQQ03nZ1qZlamvA(LOC3, key0);
	LA2: ;
	result0 = LOC1;
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result0;
}

N_NIMCALL(NI, len_6bMoxDMwI4Nef9a1VY5tbmw)(Selector_X89cGFWVbzYzXTnuQzGngmA* s0) {
	NI result0;
	nimfr("len", "selectors.nim")
{	result0 = (NI)0;
	nimln(381, "selectors.nim");
	result0 = len_Q1GsJskrVK5e0DS9cZT9bODg((*s0).fds);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result0;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_selectorsInit000)(void) {
	nimfr("selectors", "selectors.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_selectorsDatInit000)(void) {
static TNimNode* T_ln5vuDpFyDrAqQbYD2g52Q_2[3];
static TNimNode* T_ln5vuDpFyDrAqQbYD2g52Q_3[3];
NI T_ln5vuDpFyDrAqQbYD2g52Q_5;
static char* NIM_CONST T_ln5vuDpFyDrAqQbYD2g52Q_4[3] = {
"EvRead", 
"EvWrite", 
"EvError"};
static TNimNode* T_ln5vuDpFyDrAqQbYD2g52Q_14[2];
static TNimNode* T_ln5vuDpFyDrAqQbYD2g52Q_19[3];
static TNimNode T_ln5vuDpFyDrAqQbYD2g52Q_0[16];
NTI_gE60aCfYXV1Nf1VTfPbepw.size = sizeof(Selectorkey_gE60aCfYXV1Nf1VTfPbepw);
NTI_gE60aCfYXV1Nf1VTfPbepw.kind = 18;
NTI_gE60aCfYXV1Nf1VTfPbepw.base = 0;
T_ln5vuDpFyDrAqQbYD2g52Q_2[0] = &T_ln5vuDpFyDrAqQbYD2g52Q_0[1];
T_ln5vuDpFyDrAqQbYD2g52Q_0[1].kind = 1;
T_ln5vuDpFyDrAqQbYD2g52Q_0[1].offset = offsetof(Selectorkey_gE60aCfYXV1Nf1VTfPbepw, fd);
T_ln5vuDpFyDrAqQbYD2g52Q_0[1].typ = (&NTI_nlCscttRCss70IBTyuBqnA);
T_ln5vuDpFyDrAqQbYD2g52Q_0[1].name = "fd";
T_ln5vuDpFyDrAqQbYD2g52Q_2[1] = &T_ln5vuDpFyDrAqQbYD2g52Q_0[2];
NTI_nI40bZzTyYVrl763dZ9aHDg.size = sizeof(Event_nI40bZzTyYVrl763dZ9aHDg);
NTI_nI40bZzTyYVrl763dZ9aHDg.kind = 14;
NTI_nI40bZzTyYVrl763dZ9aHDg.base = 0;
NTI_nI40bZzTyYVrl763dZ9aHDg.flags = 3;
for (T_ln5vuDpFyDrAqQbYD2g52Q_5 = 0; T_ln5vuDpFyDrAqQbYD2g52Q_5 < 3; T_ln5vuDpFyDrAqQbYD2g52Q_5++) {
T_ln5vuDpFyDrAqQbYD2g52Q_0[T_ln5vuDpFyDrAqQbYD2g52Q_5+3].kind = 1;
T_ln5vuDpFyDrAqQbYD2g52Q_0[T_ln5vuDpFyDrAqQbYD2g52Q_5+3].offset = T_ln5vuDpFyDrAqQbYD2g52Q_5;
T_ln5vuDpFyDrAqQbYD2g52Q_0[T_ln5vuDpFyDrAqQbYD2g52Q_5+3].name = T_ln5vuDpFyDrAqQbYD2g52Q_4[T_ln5vuDpFyDrAqQbYD2g52Q_5];
T_ln5vuDpFyDrAqQbYD2g52Q_3[T_ln5vuDpFyDrAqQbYD2g52Q_5] = &T_ln5vuDpFyDrAqQbYD2g52Q_0[T_ln5vuDpFyDrAqQbYD2g52Q_5+3];
}
T_ln5vuDpFyDrAqQbYD2g52Q_0[6].len = 3; T_ln5vuDpFyDrAqQbYD2g52Q_0[6].kind = 2; T_ln5vuDpFyDrAqQbYD2g52Q_0[6].sons = &T_ln5vuDpFyDrAqQbYD2g52Q_3[0];
NTI_nI40bZzTyYVrl763dZ9aHDg.node = &T_ln5vuDpFyDrAqQbYD2g52Q_0[6];
NTI_YIRsZrDT89buh37M5yeUgng.size = sizeof(Event_nI40bZzTyYVrl763dZ9aHDg_Set);
NTI_YIRsZrDT89buh37M5yeUgng.kind = 19;
NTI_YIRsZrDT89buh37M5yeUgng.base = (&NTI_nI40bZzTyYVrl763dZ9aHDg);
NTI_YIRsZrDT89buh37M5yeUgng.flags = 3;
T_ln5vuDpFyDrAqQbYD2g52Q_0[7].len = 0; T_ln5vuDpFyDrAqQbYD2g52Q_0[7].kind = 0;
NTI_YIRsZrDT89buh37M5yeUgng.node = &T_ln5vuDpFyDrAqQbYD2g52Q_0[7];
T_ln5vuDpFyDrAqQbYD2g52Q_0[2].kind = 1;
T_ln5vuDpFyDrAqQbYD2g52Q_0[2].offset = offsetof(Selectorkey_gE60aCfYXV1Nf1VTfPbepw, events);
T_ln5vuDpFyDrAqQbYD2g52Q_0[2].typ = (&NTI_YIRsZrDT89buh37M5yeUgng);
T_ln5vuDpFyDrAqQbYD2g52Q_0[2].name = "events";
T_ln5vuDpFyDrAqQbYD2g52Q_2[2] = &T_ln5vuDpFyDrAqQbYD2g52Q_0[8];
T_ln5vuDpFyDrAqQbYD2g52Q_0[8].kind = 1;
T_ln5vuDpFyDrAqQbYD2g52Q_0[8].offset = offsetof(Selectorkey_gE60aCfYXV1Nf1VTfPbepw, data);
T_ln5vuDpFyDrAqQbYD2g52Q_0[8].typ = (&NTI_1VeTzqrFu2VJ4a6cGvuoyA);
T_ln5vuDpFyDrAqQbYD2g52Q_0[8].name = "data";
T_ln5vuDpFyDrAqQbYD2g52Q_0[0].len = 3; T_ln5vuDpFyDrAqQbYD2g52Q_0[0].kind = 2; T_ln5vuDpFyDrAqQbYD2g52Q_0[0].sons = &T_ln5vuDpFyDrAqQbYD2g52Q_2[0];
NTI_gE60aCfYXV1Nf1VTfPbepw.node = &T_ln5vuDpFyDrAqQbYD2g52Q_0[0];
NTI_nEEz1gjcivYloysklmeNTg.size = sizeof(TY_nEEz1gjcivYloysklmeNTg);
NTI_nEEz1gjcivYloysklmeNTg.kind = 18;
NTI_nEEz1gjcivYloysklmeNTg.base = 0;
T_ln5vuDpFyDrAqQbYD2g52Q_14[0] = &T_ln5vuDpFyDrAqQbYD2g52Q_0[10];
T_ln5vuDpFyDrAqQbYD2g52Q_0[10].kind = 1;
T_ln5vuDpFyDrAqQbYD2g52Q_0[10].offset = offsetof(TY_nEEz1gjcivYloysklmeNTg, Field0);
T_ln5vuDpFyDrAqQbYD2g52Q_0[10].typ = (&NTI_gE60aCfYXV1Nf1VTfPbepw);
T_ln5vuDpFyDrAqQbYD2g52Q_0[10].name = "Field0";
T_ln5vuDpFyDrAqQbYD2g52Q_14[1] = &T_ln5vuDpFyDrAqQbYD2g52Q_0[11];
T_ln5vuDpFyDrAqQbYD2g52Q_0[11].kind = 1;
T_ln5vuDpFyDrAqQbYD2g52Q_0[11].offset = offsetof(TY_nEEz1gjcivYloysklmeNTg, Field1);
T_ln5vuDpFyDrAqQbYD2g52Q_0[11].typ = (&NTI_YIRsZrDT89buh37M5yeUgng);
T_ln5vuDpFyDrAqQbYD2g52Q_0[11].name = "Field1";
T_ln5vuDpFyDrAqQbYD2g52Q_0[9].len = 2; T_ln5vuDpFyDrAqQbYD2g52Q_0[9].kind = 2; T_ln5vuDpFyDrAqQbYD2g52Q_0[9].sons = &T_ln5vuDpFyDrAqQbYD2g52Q_14[0];
NTI_nEEz1gjcivYloysklmeNTg.node = &T_ln5vuDpFyDrAqQbYD2g52Q_0[9];
NTI_bkMUR8maranmy38dEG39cHA.size = sizeof(TY_bkMUR8maranmy38dEG39cHA*);
NTI_bkMUR8maranmy38dEG39cHA.kind = 24;
NTI_bkMUR8maranmy38dEG39cHA.base = (&NTI_nEEz1gjcivYloysklmeNTg);
NTI_bkMUR8maranmy38dEG39cHA.marker = Marker_TY_bkMUR8maranmy38dEG39cHA;
NTI_X89cGFWVbzYzXTnuQzGngmA.size = sizeof(Selector_X89cGFWVbzYzXTnuQzGngmA);
NTI_X89cGFWVbzYzXTnuQzGngmA.kind = 18;
NTI_X89cGFWVbzYzXTnuQzGngmA.base = 0;
T_ln5vuDpFyDrAqQbYD2g52Q_19[0] = &T_ln5vuDpFyDrAqQbYD2g52Q_0[13];
T_ln5vuDpFyDrAqQbYD2g52Q_0[13].kind = 1;
T_ln5vuDpFyDrAqQbYD2g52Q_0[13].offset = offsetof(Selector_X89cGFWVbzYzXTnuQzGngmA, kqfd);
T_ln5vuDpFyDrAqQbYD2g52Q_0[13].typ = (&NTI_nlCscttRCss70IBTyuBqnA);
T_ln5vuDpFyDrAqQbYD2g52Q_0[13].name = "kqFD";
T_ln5vuDpFyDrAqQbYD2g52Q_19[1] = &T_ln5vuDpFyDrAqQbYD2g52Q_0[14];
NTI_80NdCG41SyhPocFo20IbDw.size = sizeof(TY_80NdCG41SyhPocFo20IbDw);
NTI_80NdCG41SyhPocFo20IbDw.kind = 16;
NTI_80NdCG41SyhPocFo20IbDw.base = (&NTI_9cG9coEVt8bUEuxUupPPZigQ);
NTI_80NdCG41SyhPocFo20IbDw.flags = 3;
T_ln5vuDpFyDrAqQbYD2g52Q_0[14].kind = 1;
T_ln5vuDpFyDrAqQbYD2g52Q_0[14].offset = offsetof(Selector_X89cGFWVbzYzXTnuQzGngmA, events);
T_ln5vuDpFyDrAqQbYD2g52Q_0[14].typ = (&NTI_80NdCG41SyhPocFo20IbDw);
T_ln5vuDpFyDrAqQbYD2g52Q_0[14].name = "events";
T_ln5vuDpFyDrAqQbYD2g52Q_19[2] = &T_ln5vuDpFyDrAqQbYD2g52Q_0[15];
T_ln5vuDpFyDrAqQbYD2g52Q_0[15].kind = 1;
T_ln5vuDpFyDrAqQbYD2g52Q_0[15].offset = offsetof(Selector_X89cGFWVbzYzXTnuQzGngmA, fds);
T_ln5vuDpFyDrAqQbYD2g52Q_0[15].typ = (&NTI_bnna5wr180tUeaeDFxJ4xA);
T_ln5vuDpFyDrAqQbYD2g52Q_0[15].name = "fds";
T_ln5vuDpFyDrAqQbYD2g52Q_0[12].len = 3; T_ln5vuDpFyDrAqQbYD2g52Q_0[12].kind = 2; T_ln5vuDpFyDrAqQbYD2g52Q_0[12].sons = &T_ln5vuDpFyDrAqQbYD2g52Q_19[0];
NTI_X89cGFWVbzYzXTnuQzGngmA.node = &T_ln5vuDpFyDrAqQbYD2g52Q_0[12];
}

